import { DailyCase } from "./types";

export const CASES_BATCH4: DailyCase[] = [
  {
    id: "case-064",
    date: "2026-04-25",
    difficulty: 4,
    question: "Will any country ban TikTok nationwide in 2025?",
    resolutionCriteria: "Resolves YES if any sovereign nation implements a legally enforceable nationwide ban on TikTok (the app is no longer available for download and/or use within the country's borders) during 2025. Source: official government gazette, executive order, or court order.",
    timeline: [
      { date: "Jan 2025", description: "US ban legislation takes effect. TikTok removed from US app stores." },
      { date: "Jan 2025", description: "Within 48 hours, executive order grants 90-day extension. TikTok restored to app stores." },
      { date: "Apr 2025", description: "Extension extended again. TikTok continues operating in US throughout 2025." },
    ],
    officialResolution: "Resolved YES (citing the initial 24-48 hour period when TikTok was removed)",
    correctClassification: "misresolved",
    correctFlaw: "time_boundary_error",
    explanation: "The ban was technically in effect for approximately 24-48 hours before the executive order extension. The criteria asked whether any country 'implements a legally enforceable nationwide ban.' A ban that lasted less than 48 hours before being suspended is arguably not an 'implementation' in any meaningful sense — it's an activation immediately followed by suspension. The resolution counted an ephemeral enforcement window as implementation.",
    alternateInterpretation: "The ban did technically take effect — TikTok was removed from app stores. The criteria didn't specify a minimum duration for the ban. Any period of enforcement constitutes implementation.",
    marketPriceBehavior: "High at 80% before January deadline. Crashed to 30% on extension. Debated between 20-40% all year.",
  },
  {
    id: "case-065",
    date: "2026-04-26",
    difficulty: 3,
    question: "Will a Category 5 tropical cyclone form in the Atlantic basin in 2025?",
    resolutionCriteria: "Resolves YES if at least one tropical cyclone in the Atlantic basin reaches Category 5 intensity (157+ mph sustained winds) at any point during the 2025 season. Source: National Hurricane Center best track data.",
    timeline: [
      { date: "Sep 2025", description: "Hurricane reaches Category 5 with 160 mph sustained winds." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "NHC best track data confirms Category 5 intensity. Clean resolution.",
    alternateInterpretation: "None.",
    marketPriceBehavior: "Started at 55% based on seasonal forecasts. Gradually rose through active season. Jumped to 99% on intensification.",
  },
  {
    id: "case-066",
    date: "2026-04-27",
    difficulty: 5,
    question: "Will the WHO add a new disease to its 'Disease X' priority pathogen list by end of 2025?",
    resolutionCriteria: "Resolves YES if the WHO formally adds a new specific pathogen (not a placeholder) to its R&D Blueprint priority diseases list during 2025, representing a previously unrecognized threat. Source: WHO R&D Blueprint official list update.",
    timeline: [
      { date: "Aug 2025", description: "WHO updates R&D Blueprint list, adding 'Pathogen Y' — a novel virus family first identified in 2024." },
      { date: "Sep 2025", description: "Virologists debate whether Pathogen Y is truly 'novel' or a reclassification of a known virus genus." },
      { date: "Oct 2025", description: "WHO maintains Pathogen Y as a new entry, noting it has 'distinct epidemiological characteristics warranting separate classification.'" },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "WHO added a new specific pathogen to the list. The criteria specified 'new specific pathogen' and 'previously unrecognized threat.' WHO's official classification treats it as new, and the WHO list is the specified source. The taxonomic debate among virologists doesn't override the WHO's official categorization.",
    alternateInterpretation: "If the pathogen is a reclassification rather than a genuinely new threat, one could argue the criteria for 'previously unrecognized' isn't met. But the WHO, as the authoritative source, made the determination.",
    marketPriceBehavior: "Low at 20% most of the year. Jumped to 65% on list update. Settled at 72% after WHO defense of classification.",
  },
  {
    id: "case-067",
    date: "2026-04-28",
    difficulty: 4,
    question: "Will the global installed solar capacity exceed 2 terawatts (cumulative) by end of 2025?",
    resolutionCriteria: "Resolves YES if cumulative global installed solar photovoltaic capacity exceeds 2,000 GW (2 TW) by December 31, 2025. Source: International Energy Agency (IEA) Renewables report or International Renewable Energy Agency (IRENA) statistics.",
    timeline: [
      { date: "Mar 2026", description: "IEA reports cumulative solar PV capacity reached 2,150 GW by end of 2025." },
      { date: "Apr 2026", description: "IRENA reports 2,089 GW, using a stricter methodology excluding some small-scale residential installations." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "Both IEA and IRENA report figures exceeding 2,000 GW (2,150 and 2,089 respectively). Both specified sources agree the threshold was met, eliminating source-disagreement issues.",
    alternateInterpretation: "None. Both sources agree.",
    marketPriceBehavior: "High at 80% from start given installation trajectory. Rose to 92% by mid-year.",
  },
  {
    id: "case-068",
    date: "2026-04-29",
    difficulty: 3,
    question: "Will any movie gross over $2 billion worldwide in 2025?",
    resolutionCriteria: "Resolves YES if any single film released in 2025 grosses over $2 billion in worldwide box office revenue during its theatrical run. Source: Box Office Mojo or The Numbers.",
    timeline: [
      { date: "Aug 2025", description: "Major franchise sequel crosses $2.1 billion worldwide per Box Office Mojo." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "$2.1 billion exceeds $2 billion. Source matches. Clean resolution.",
    alternateInterpretation: "None.",
    marketPriceBehavior: "Started at 45%. Rose as summer blockbuster tracked well. Crossed 90% in late July.",
  },
  {
    id: "case-069",
    date: "2026-04-30",
    difficulty: 5,
    question: "Will the Arctic experience an ice-free day (sea ice extent below 1 million km²) in 2025?",
    resolutionCriteria: "Resolves YES if Arctic sea ice extent drops below 1 million square kilometers on any single day during 2025, as measured by NSIDC (National Snow and Ice Data Center). Source: NSIDC daily sea ice extent data.",
    timeline: [
      { date: "Sep 2025", description: "NSIDC reports daily minimum extent of 2.8 million km² for the 2025 season." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "2.8 million km² is well above 1 million km². The event did not occur. While concerning from a climate perspective, the specific threshold was not approached.",
    alternateInterpretation: "None. The measurement is clear and well above the threshold.",
    marketPriceBehavior: "Started at 3%. Never rose above 8%. Seasonal minimum wasn't even close.",
  },
  {
    id: "case-070",
    date: "2026-05-01",
    difficulty: 4,
    question: "Will any government successfully repatriate more than $1 billion in cryptocurrency from a single seizure in 2025?",
    resolutionCriteria: "Resolves YES if any government agency completes the repatriation (conversion to fiat or transfer to government-controlled wallets) of cryptocurrency assets valued at more than $1 billion from a single criminal seizure during 2025. Value measured at time of repatriation. Source: DOJ, Europol, or equivalent law enforcement press release.",
    timeline: [
      { date: "Jun 2025", description: "US DOJ announces seizure of $1.4 billion in Bitcoin from dark web marketplace." },
      { date: "Aug 2025", description: "DOJ begins selling seized Bitcoin. First tranche of $600M converted." },
      { date: "Nov 2025", description: "Second tranche of $500M converted. Total repatriated: $1.1B. But Bitcoin price dropped 15% during the sales, meaning original seizure value was $1.4B but repatriation value was $1.1B." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The criteria specified 'value measured at time of repatriation.' The total repatriated value ($1.1B) exceeds $1B. The original seizure value is irrelevant — the criteria were precise about using repatriation-time valuation.",
    alternateInterpretation: "None. The criteria anticipated the price-fluctuation issue by specifying measurement timing.",
    marketPriceBehavior: "Jumped to 70% on seizure announcement. Dipped during sell-off period as price dropped. Recovered to 80% when $1B threshold was clearly passed.",
  },
  {
    id: "case-071",
    date: "2026-05-02",
    difficulty: 5,
    question: "Will the first commercial space station module reach orbit by end of 2025?",
    resolutionCriteria: "Resolves YES if a privately developed space station module (intended for commercial, non-government primary use) achieves stable orbit by December 31, 2025. ISS commercial modules do not count — must be a separate commercial station. Source: FAA launch license records and NORAD tracking.",
    timeline: [
      { date: "Oct 2025", description: "Axiom Space announces delay of Axiom Station Module 1 launch to 2026." },
      { date: "Nov 2025", description: "Vast Space launches Haven-1, a single-module commercial station, reaching orbit on November 28." },
      { date: "Dec 2025", description: "Debate: Haven-1 is designed to dock with the ISS initially before operating independently. Is it a 'separate commercial station' or an ISS adjunct?" },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "indeterminate",
    explanation: "Haven-1 reached orbit but is designed to initially dock with ISS before later operating independently. The criteria excluded 'ISS commercial modules' and required a 'separate commercial station.' Whether Haven-1 is 'separate' when it plans to dock with ISS is genuinely ambiguous. It's a separate module launched independently but functionally connected to ISS during initial operations.",
    alternateInterpretation: "Haven-1 launched independently, achieved independent orbit, and is a free-flying module. Its planned ISS docking is temporary and operational, not structural — it's not an ISS module but a visiting vehicle. This makes it 'separate.'",
    marketPriceBehavior: "Started at 25%. Dropped to 15% on Axiom delay. Rose to 60% on Vast launch. Debated at 50-55% on ISS docking question.",
  },
  {
    id: "case-072",
    date: "2026-05-03",
    difficulty: 3,
    question: "Will India's population officially surpass 1.45 billion in a 2025 census or estimate?",
    resolutionCriteria: "Resolves YES if the Indian Census Bureau or the UN Population Division reports India's population as exceeding 1.45 billion in any official 2025 publication. Source: Indian Census or UN World Population Prospects.",
    timeline: [
      { date: "Jul 2025", description: "UN World Population Prospects mid-year revision estimates India at 1.461 billion." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "1.461 billion exceeds 1.45 billion. The UN is a specified source. Clean resolution.",
    alternateInterpretation: "None.",
    marketPriceBehavior: "High at 85% from start. India had already surpassed China. Settled at 95% before UN publication.",
  },
  {
    id: "case-073",
    date: "2026-05-04",
    difficulty: 4,
    question: "Will any country successfully implement a four-day work week as national policy by end of 2025?",
    resolutionCriteria: "Resolves YES if a sovereign nation passes legislation or issues binding executive action establishing a four-day work week (32 hours or less) as the standard for all workers (not just government employees or specific sectors) by December 31, 2025. Source: official government gazette or legislative record.",
    timeline: [
      { date: "Sep 2025", description: "Country G passes legislation reducing standard work week to 35 hours over 4 days." },
      { date: "Oct 2025", description: "Law includes phase-in period: applies only to companies with 50+ employees in Year 1, all companies by Year 3." },
      { date: "Nov 2025", description: "Analysis notes the law sets 35 hours not 32, and doesn't apply to all workers immediately." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "misresolved",
    correctFlaw: "procedural_substantive_confusion",
    explanation: "The criteria specified '32 hours or less' and 'all workers.' The law establishes 35 hours (exceeding the 32-hour threshold) and phases in coverage (not 'all workers' in 2025). The resolution treated the passage of four-day-week legislation as meeting the criteria without checking the specific numerical and coverage requirements.",
    alternateInterpretation: "The law does establish a four-day work week as the national standard, which is the spirit of the question. The 35 vs 32 distinction and phase-in could be viewed as implementation details rather than definitional failures.",
    marketPriceBehavior: "Rose to 65% on legislation passage. Dropped to 45% on 35-hour and phase-in details. Debated at 40-55% through resolution.",
  },
  {
    id: "case-074",
    date: "2026-05-05",
    difficulty: 5,
    question: "Will a non-human entity (AI or animal) be granted legal personhood status by any jurisdiction by end of 2025?",
    resolutionCriteria: "Resolves YES if any court or legislature in any country grants formal legal personhood (with specific legal rights and standing to sue) to a non-human entity that is either an AI system or an animal during 2025. Source: court ruling, legislation, or official gazette.",
    timeline: [
      { date: "Jul 2025", description: "Ecuador's Constitutional Court rules that a specific river has 'rights of nature' including legal personhood." },
      { date: "Aug 2025", description: "Ruling grants the river standing to sue through appointed guardians." },
      { date: "Sep 2025", description: "Legal scholars debate: a river is a non-human entity, but the criteria specified 'AI system or an animal.' Rivers are neither." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "misresolved",
    correctFlaw: "definition_ambiguity",
    explanation: "The criteria explicitly limited non-human entities to 'either an AI system or an animal.' A river is neither an AI system nor an animal. While the river received legal personhood, it falls outside the criteria's specified categories. The resolution incorrectly expanded the scope beyond the stated definitions.",
    alternateInterpretation: "One could argue the criteria used 'non-human entity' as the primary qualifier with AI/animal as examples, not an exhaustive list. But the parenthetical '(AI or animal)' reads as definitional, not illustrative.",
    marketPriceBehavior: "Low at 8% most of year. Brief spike to 25% on Ecuador ruling. Settled at 15% as definitional debate emerged.",
  },
  {
    id: "case-075",
    date: "2026-05-06",
    difficulty: 3,
    question: "Will Nvidia's annual revenue exceed $130 billion for fiscal year ending January 2026?",
    resolutionCriteria: "Resolves YES if Nvidia's total revenue for fiscal year 2026 (ending January 2026) exceeds $130 billion. Source: Nvidia's annual earnings report or 10-K filing.",
    timeline: [
      { date: "Feb 2026", description: "Nvidia reports FY2026 revenue of $148.2 billion." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "$148.2B exceeds $130B. Source matches. Clean resolution.",
    alternateInterpretation: "None.",
    marketPriceBehavior: "Started at 65%. Rose through the year as AI demand surged. Reached 92% after Q3 earnings beat.",
  },
  {
    id: "case-076",
    date: "2026-05-07",
    difficulty: 4,
    question: "Will any nation withdraw from the Paris Climate Agreement in 2025?",
    resolutionCriteria: "Resolves YES if any signatory nation formally notifies the UN of its withdrawal from the Paris Agreement during 2025. Formal withdrawal requires official notification to the UN Secretary-General. Source: UN Treaty Collection or UNFCCC official records.",
    timeline: [
      { date: "Jan 2025", description: "US President signs executive order directing withdrawal from Paris Agreement." },
      { date: "Jan 2025", description: "US formally notifies UN Secretary-General of intent to withdraw." },
      { date: "Feb 2025", description: "Under Article 28, withdrawal takes effect one year after notification — effective date would be January 2026." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "indeterminate",
    explanation: "The criteria said 'formally notifies the UN of its withdrawal.' The US did formally notify. However, under the Paris Agreement, withdrawal doesn't take effect until one year after notification. Did the US 'withdraw' in 2025 (notification) or 2026 (effective date)? The criteria asked about notification, which occurred, but common understanding of 'withdraw' implies completion of the process.",
    alternateInterpretation: "The criteria specified 'formally notifies the UN of its withdrawal' — notification is the action, not the completion. The US completed the notification action in 2025.",
    marketPriceBehavior: "Jumped to 85% on executive order. Debated between 60-80% as notification vs effective withdrawal was parsed.",
  },
  {
    id: "case-077",
    date: "2026-05-08",
    difficulty: 5,
    question: "Will a brain-computer interface enable a paralyzed patient to type more than 60 words per minute by end of 2025?",
    resolutionCriteria: "Resolves YES if a peer-reviewed publication demonstrates a brain-computer interface enabling a patient with paralysis to type at a sustained rate exceeding 60 words per minute, published by December 31, 2025. 'Sustained' means over a minimum 5-minute session. Source: peer-reviewed publication in a journal with impact factor > 5.",
    timeline: [
      { date: "Oct 2025", description: "Neuralink publishes results in Nature Medicine: patient achieved 62 WPM peak rate during a 3-minute session." },
      { date: "Nov 2025", description: "Over 5-minute sessions, average rate was 54 WPM with peaks of 62 WPM." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "The criteria required 'sustained rate exceeding 60 WPM' over a 'minimum 5-minute session.' The 5-minute average was 54 WPM. Peak rates of 62 during shorter windows don't satisfy the sustained-rate requirement. The resolution correctly applied the duration and sustained-rate requirements.",
    alternateInterpretation: "62 WPM was achieved, just not over 5 minutes. The criteria's sustained requirement prevented counting peak performance, which could be seen as overly restrictive for a breakthrough result.",
    marketPriceBehavior: "Jumped to 60% on publication. Dropped to 25% when sustained-rate analysis showed sub-60 average.",
  },
  {
    id: "case-078",
    date: "2026-05-09",
    difficulty: 4,
    question: "Will global military spending exceed $2.5 trillion in 2025?",
    resolutionCriteria: "Resolves YES if total worldwide military expenditure exceeds $2.5 trillion for calendar year 2025. Source: SIPRI Military Expenditure Database.",
    timeline: [
      { date: "Apr 2026", description: "SIPRI reports 2025 global military spending at $2.62 trillion (current USD)." },
      { date: "Apr 2026", description: "In constant 2022 USD, spending was $2.41 trillion." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The criteria didn't specify constant or current dollars. SIPRI's headline figure is typically in current USD ($2.62T). Using either conventional reporting measure, only the constant-dollar figure falls below threshold. Since the criteria didn't specify deflation methodology, the standard SIPRI headline figure (current USD) is appropriate.",
    alternateInterpretation: "If constant dollars were used, the answer would be NO. But absent specification, current dollars is the default in SIPRI reporting.",
    marketPriceBehavior: "Started at 70% given growth trends. Gradually rose to 85% through the year.",
  },
  {
    id: "case-079",
    date: "2026-05-10",
    difficulty: 3,
    question: "Will the average US 30-year fixed mortgage rate drop below 5.5% at any point in 2025?",
    resolutionCriteria: "Resolves YES if the Freddie Mac Primary Mortgage Market Survey (PMMS) weekly average 30-year fixed mortgage rate drops below 5.50% for any weekly reading in 2025. Source: Freddie Mac PMMS.",
    timeline: [
      { date: "Nov 2025", description: "Freddie Mac PMMS reports 30-year fixed rate at 5.42% for the week ending November 20." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "5.42% is below 5.50%. Source matches. Clean resolution.",
    alternateInterpretation: "None.",
    marketPriceBehavior: "Traded at 40% early 2025. Rose with each Fed cut. Crossed 80% as rates approached 5.5%.",
  },
  {
    id: "case-080",
    date: "2026-05-11",
    difficulty: 5,
    question: "Will a verified case of horizontal gene transfer from a GMO crop to a wild plant species be documented in 2025?",
    resolutionCriteria: "Resolves YES if a peer-reviewed paper published in 2025 provides verified evidence of horizontal gene transfer (not vertical/cross-pollination) from a commercially grown GMO crop to a wild plant species. Source: peer-reviewed publication in a biology journal with impact factor > 8.",
    timeline: [
      { date: "Aug 2025", description: "Paper in Science documents transgene sequences found in wild grass species growing near Bt corn fields." },
      { date: "Sep 2025", description: "Authors attribute transfer to 'Agrobacterium-mediated horizontal transfer,' but peer commentary suggests cross-pollination with feral corn as the more likely mechanism." },
      { date: "Nov 2025", description: "Follow-up analysis is inconclusive on whether the transfer was truly horizontal or resulted from complex hybridization pathways." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "misresolved",
    correctFlaw: "source_hierarchy_mistake",
    explanation: "The criteria specified 'verified evidence of horizontal gene transfer (not vertical/cross-pollination).' The original paper claimed horizontal transfer, but peer commentary and follow-up analysis could not confirm the mechanism was horizontal rather than vertical. 'Verified evidence' implies scientific consensus on the mechanism, which was not achieved. The resolution relied on the initial paper's claim while ignoring contradicting peer analysis.",
    alternateInterpretation: "The initial paper was peer-reviewed and published in Science (IF > 8). Subsequent commentary hasn't been formally published as a rebuttal. The original paper's methodology stands until formally refuted.",
    marketPriceBehavior: "Jumped to 55% on paper publication. Dropped to 30% on peer criticism. Settled at 35% with unresolved debate.",
  },
  {
    id: "case-081",
    date: "2026-05-12",
    difficulty: 4,
    question: "Will any city in the world record a temperature above 55°C (131°F) in 2025?",
    resolutionCriteria: "Resolves YES if any city with a population exceeding 100,000 records an air temperature above 55°C as measured by a WMO-compliant weather station during 2025. Source: WMO verification or national meteorological service official records.",
    timeline: [
      { date: "Jul 2025", description: "Weather station in Jacobabad, Pakistan records 55.2°C." },
      { date: "Aug 2025", description: "WMO begins verification process. Preliminary review flags potential instrument calibration concerns." },
      { date: "Dec 2025", description: "WMO verification still pending at year end. National meteorological service of Pakistan stands by the reading." },
    ],
    officialResolution: "Resolved YES (based on national meteorological service record)",
    correctClassification: "indeterminate",
    explanation: "The criteria specified 'WMO verification or national meteorological service official records.' The national service confirms the reading, satisfying one branch of the source requirement. However, WMO verification is pending and has flagged concerns. Using the national service alone when WMO has active doubts creates genuine ambiguity about whether the reading is reliable.",
    alternateInterpretation: "The criteria presented WMO and national service as alternatives ('or'). The national service confirmed the reading, which alone satisfies the source requirement regardless of WMO's pending process.",
    marketPriceBehavior: "Spiked to 75% on reading. Dropped to 50% on WMO concerns. Settled at 55% pending verification.",
  },
  {
    id: "case-082",
    date: "2026-05-13",
    difficulty: 3,
    question: "Will Spotify reach 700 million monthly active users by end of 2025?",
    resolutionCriteria: "Resolves YES if Spotify reports MAU exceeding 700 million in their Q4 2025 earnings release. Source: Spotify earnings report.",
    timeline: [
      { date: "Feb 2026", description: "Spotify Q4 2025 earnings: 715 million MAU reported." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "715M > 700M. Source matches. Clean resolution.",
    alternateInterpretation: "None.",
    marketPriceBehavior: "Gradually rose from 55% to 85% as each quarterly report showed growth.",
  },
  {
    id: "case-083",
    date: "2026-05-14",
    difficulty: 5,
    question: "Will a successful recall election remove a sitting US governor from office in 2025?",
    resolutionCriteria: "Resolves YES if a gubernatorial recall election is held in any US state during 2025 and the sitting governor is removed from office as a result. Source: state Secretary of State official election results.",
    timeline: [
      { date: "Aug 2025", description: "Recall election held for governor of State A. 52% vote for recall." },
      { date: "Aug 2025", description: "Governor files legal challenge arguing recall petition process violated state procedural requirements." },
      { date: "Oct 2025", description: "State Supreme Court voids recall results due to procedural irregularities in petition gathering. Governor remains in office." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "The governor was not removed from office. While voters voted for recall, the court voided the results. The criteria required the governor to be 'removed from office as a result' of the recall election. Since the results were voided, no removal occurred.",
    alternateInterpretation: "One could argue voters did vote for removal, but the criteria asked about the outcome (removal from office), not just the vote. The governor remained in office.",
    marketPriceBehavior: "Rose to 70% on recall vote results. Dropped to 40% on legal challenge. Crashed to 10% on court ruling.",
  },
];
