import { DailyCase } from "./types";

export const CASES_BATCH3: DailyCase[] = [
  {
    id: "case-046",
    date: "2026-04-07",
    difficulty: 4,
    question: "Will the European Parliament pass comprehensive AI liability legislation by end of 2025?",
    resolutionCriteria: "Resolves YES if the European Parliament votes to adopt legislation establishing a comprehensive liability framework for AI systems (covering both strict and fault-based liability) by December 31, 2025. Source: European Parliament legislative tracker.",
    timeline: [
      { date: "Jun 2025", description: "Parliament votes to adopt the AI Liability Directive covering strict liability for high-risk AI systems." },
      { date: "Jul 2025", description: "Legal scholars note the Directive only covers strict liability for high-risk AI; fault-based liability for other AI systems deferred to national law." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "misresolved",
    correctFlaw: "definition_ambiguity",
    explanation: "The criteria required legislation 'covering both strict and fault-based liability.' The adopted Directive covers strict liability for high-risk AI only; fault-based liability is left to member states. The resolution appears to have treated the Directive as comprehensive when it only addresses one half of the specified scope.",
    alternateInterpretation: "The Directive does reference fault-based liability by noting member states' existing frameworks apply. Whether referencing something constitutes 'covering' it is ambiguous.",
    marketPriceBehavior: "Rose from 50% to 78% as legislative process advanced. Peaked at 85% on vote. Dropped to 65% on scope analysis.",
  },
  {
    id: "case-047",
    date: "2026-04-08",
    difficulty: 3,
    question: "Will South Korea's birth rate fall below 0.7 for 2025?",
    resolutionCriteria: "Resolves YES if South Korea's total fertility rate (TFR) for 2025 falls below 0.70, as reported by Statistics Korea. Source: Statistics Korea vital statistics report.",
    timeline: [
      { date: "Feb 2026", description: "Statistics Korea reports 2025 TFR at 0.68." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "0.68 < 0.70. Source matches. Clean resolution with no ambiguity.",
    alternateInterpretation: "None.",
    marketPriceBehavior: "Started at 65% given downward trend. Gradually rose as quarterly data came in. Settled at 88% before report.",
  },
  {
    id: "case-048",
    date: "2026-04-09",
    difficulty: 5,
    question: "Will the US government officially acknowledge the existence of a UAP (UFO) retrieval and reverse-engineering program by end of 2025?",
    resolutionCriteria: "Resolves YES if the US federal government, through an official declassified report, congressional testimony under oath, or signed Executive Order, acknowledges the existence of a program to retrieve and reverse-engineer non-human-origin craft. Source: official US government document or C-SPAN record.",
    timeline: [
      { date: "Jul 2025", description: "Congressional hearing features witnesses testifying about 'legacy retrieval programs' under oath." },
      { date: "Aug 2025", description: "Pentagon spokesperson states: 'We have found no verifiable evidence of programs related to non-human technology.'" },
      { date: "Oct 2025", description: "Inspector General report references 'unaccounted programs' related to 'exotic material analysis' but does not confirm non-human origin." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "The criteria required official acknowledgment of a program for 'non-human-origin craft.' Congressional testimony by witnesses is not the government acknowledging; the Pentagon actively denied. The IG report referenced 'exotic material' without confirming non-human origin. No official government document met the specific criteria.",
    alternateInterpretation: "One could argue congressional testimony under oath constitutes government acknowledgment since Congress is a branch of government. But the witnesses were not speaking on behalf of the government — they were testifying about their personal knowledge.",
    marketPriceBehavior: "Started at 20%. Spiked to 45% during hearings. Dropped to 15% after Pentagon denial.",
  },
  {
    id: "case-049",
    date: "2026-04-10",
    difficulty: 4,
    question: "Will any African nation's GDP growth exceed 10% in 2025?",
    resolutionCriteria: "Resolves YES if any African country achieves real GDP growth exceeding 10% for calendar year 2025, as reported by the IMF World Economic Outlook or World Bank World Development Indicators. Source: IMF WEO or World Bank WDI.",
    timeline: [
      { date: "Apr 2026", description: "IMF WEO reports Guyana at 12.4% growth. However, Guyana is in South America." },
      { date: "Apr 2026", description: "IMF reports Libya at 11.2% growth, driven by post-conflict oil production recovery." },
      { date: "May 2026", description: "World Bank WDI reports Libya at 9.8%, using a different GDP deflator methodology." },
    ],
    officialResolution: "Resolved YES (based on IMF figure for Libya)",
    correctClassification: "indeterminate",
    explanation: "The criteria specified two sources (IMF WEO or World Bank WDI) that produce different results for Libya — one above 10% and one below. As with case-030, when two specified sources disagree and the criteria treats them as alternatives, the result is genuinely indeterminate.",
    alternateInterpretation: "The 'or' could indicate either source is sufficient. If any listed source shows >10%, the condition is met under a generous reading of 'or.'",
    marketPriceBehavior: "Traded at 35% through mid-2025. Rose to 60% on Libya oil production reports. Split views at 50-55% at resolution.",
  },
  {
    id: "case-050",
    date: "2026-04-11",
    difficulty: 3,
    question: "Will Threads (Meta) reach 500 million monthly active users by end of 2025?",
    resolutionCriteria: "Resolves YES if Meta reports Threads MAU exceeding 500 million in any earnings call, press release, or SEC filing during or after Q4 2025. Source: Meta Platforms official communications.",
    timeline: [
      { date: "Jan 2026", description: "Meta Q4 2025 earnings: Mark Zuckerberg states 'Threads now has over 500 million monthly actives.'" },
      { date: "Jan 2026", description: "SEC filing does not include a specific Threads MAU figure, only stating it is 'part of the Family of Apps metrics.'" },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "CEO statement in earnings call is an official Meta communication. The criteria accepted earnings calls as a valid source. The statement clearly says 'over 500 million monthly actives.'",
    alternateInterpretation: "The lack of a precise number in SEC filings could suggest the earnings call figure is an approximation, but the criteria accepted earnings calls as sufficient.",
    marketPriceBehavior: "Gradually rose from 40% to 72% through 2025 as Threads grew. Settled at 80% before earnings.",
  },
  {
    id: "case-051",
    date: "2026-04-12",
    difficulty: 5,
    question: "Will the International Criminal Court issue an arrest warrant for a sitting head of state of a P5 country (or their close ally receiving military aid) by end of 2025?",
    resolutionCriteria: "Resolves YES if the ICC issues an arrest warrant for a sitting head of state of a UN Security Council permanent member (US, UK, France, Russia, China) or a head of state of a country receiving significant military aid (>$1B annually) from a P5 member, by December 31, 2025. Source: ICC press release.",
    timeline: [
      { date: "May 2025", description: "ICC issues arrest warrant for a head of state of Country C, which receives $3.2B in annual military aid from a P5 member." },
      { date: "Jun 2025", description: "The P5 member disputes the $3.2B figure, stating $1.8B is military aid and $1.4B is economic/humanitarian aid." },
      { date: "Jul 2025", description: "Independent analysis confirms $2.1B in military-specific aid using standard SIPRI classifications." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "Even using the most conservative military aid figure ($1.8B from the P5 member itself, or $2.1B from SIPRI), the amount exceeds the $1B threshold. The ICC warrant was issued for a sitting head of state. All criteria are met regardless of which aid classification is used.",
    alternateInterpretation: "The dispute over aid categorization is real but doesn't affect the outcome since all estimates exceed the $1B threshold by a wide margin.",
    marketPriceBehavior: "Started at 40%. Rose to 75% on warrant announcement. Brief dip on aid classification debate. Settled at 82%.",
  },
  {
    id: "case-052",
    date: "2026-04-13",
    difficulty: 4,
    question: "Will a major tech company (market cap >$500B) face a forced breakup or structural separation order from any government by end of 2025?",
    resolutionCriteria: "Resolves YES if any technology company with market capitalization exceeding $500 billion receives a legally binding order from a court or regulatory body requiring corporate breakup, structural separation, or forced divestiture of a major business unit. Order must be issued (not just proposed) by December 31, 2025. Source: court filing or regulatory order.",
    timeline: [
      { date: "Aug 2025", description: "US federal judge issues 'final judgment' in antitrust case against Company D, ordering divestiture of its advertising technology business." },
      { date: "Sep 2025", description: "Company D files appeal. Divestiture order is stayed pending appeal." },
      { date: "Oct 2025", description: "Legal analysts note the order was 'issued' but is not 'enforceable' due to the stay." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The criteria specified the order must be 'issued,' not enforced or implemented. A court order that is issued and then stayed pending appeal was still issued. The stay affects enforcement timing but not the fact that the order exists. The criteria were precise about the issuance requirement.",
    alternateInterpretation: "One could argue a stayed order is not 'legally binding' in practical terms since it cannot be enforced. But the order itself is a binding legal instrument — the stay is a separate procedural mechanism.",
    marketPriceBehavior: "Rose from 25% to 70% through the trial. Jumped to 90% on judgment. Brief dip to 80% on appeal filing.",
  },
  {
    id: "case-053",
    date: "2026-04-14",
    difficulty: 3,
    question: "Will the global average CO2 concentration exceed 430 ppm for any month in 2025?",
    resolutionCriteria: "Resolves YES if the monthly average atmospheric CO2 concentration at Mauna Loa Observatory exceeds 430 parts per million for any month in 2025. Source: NOAA Global Monitoring Laboratory monthly data.",
    timeline: [
      { date: "May 2025", description: "NOAA reports May 2025 monthly average CO2 at 431.2 ppm at Mauna Loa." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "431.2 > 430 ppm. Source is NOAA Mauna Loa as specified. May is the typical seasonal peak. Clean resolution.",
    alternateInterpretation: "None. Straightforward measurement against clear threshold.",
    marketPriceBehavior: "High at 80% from the start given upward trend. Rose to 95% by April.",
  },
  {
    id: "case-054",
    date: "2026-04-15",
    difficulty: 5,
    question: "Will a commercial airline accident kill more than 200 people in a single incident in 2025?",
    resolutionCriteria: "Resolves YES if a commercial airline accident (scheduled passenger service by IATA member airline) results in more than 200 fatalities in a single incident during 2025. Source: Aviation Safety Network database or official accident investigation report.",
    timeline: [
      { date: "Nov 2025", description: "Aircraft operated by an IATA member airline crashes. Initial reports cite 208 fatalities including 195 passengers, 8 crew, and 5 ground victims." },
      { date: "Dec 2025", description: "Official investigation preliminary report confirms 203 passenger and crew fatalities. 5 ground fatalities classified separately as 'third-party fatalities.'" },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "indeterminate",
    explanation: "The criteria specified 'more than 200 fatalities in a single incident' without specifying whether ground fatalities count. Aviation Safety Network typically separates occupant and ground fatalities. If only occupant fatalities count: 203 (YES). If all fatalities count: 208 (YES). But if the question is about the aircraft accident's direct victims (occupants only), the 5 ground fatalities are in a gray area that the criteria didn't address.",
    alternateInterpretation: "Both counts exceed 200, so the resolution of YES is correct regardless of ground fatality classification. The indeterminacy is academic in this case.",
    marketPriceBehavior: "Very low at 5% most of the year (aviation safety has been excellent). Spiked to 99% after accident.",
  },
  {
    id: "case-055",
    date: "2026-04-16",
    difficulty: 4,
    question: "Will the US impose tariffs exceeding 25% on all Chinese imports by end of 2025?",
    resolutionCriteria: "Resolves YES if the US imposes tariffs of 25% or higher on all categories of Chinese imports (no exemptions for any product category) by December 31, 2025. Source: US Trade Representative or Federal Register notice.",
    timeline: [
      { date: "Mar 2025", description: "US announces 25% tariff on all Chinese imports effective immediately." },
      { date: "Apr 2025", description: "USTR issues product exclusion list exempting certain medical devices, rare earth minerals, and semiconductor manufacturing equipment." },
      { date: "Jun 2025", description: "Administration states tariffs apply to '97% of Chinese imports by value.'" },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "misresolved",
    correctFlaw: "definition_ambiguity",
    explanation: "The criteria stated 'all categories of Chinese imports (no exemptions for any product category).' The exclusion list explicitly exempts certain product categories. 97% coverage is not 'all.' The resolution ignored the specific 'no exemptions' language in the criteria.",
    alternateInterpretation: "97% coverage could be considered functionally equivalent to 'all' in trade policy terms, where some de minimis exemptions are standard practice.",
    marketPriceBehavior: "Spiked to 90% on tariff announcement. Dropped to 65% when exclusion list was published. Settled at 55% amid debate.",
  },
  {
    id: "case-056",
    date: "2026-04-17",
    difficulty: 3,
    question: "Will any women's professional sports league average more than 10,000 fans per game in 2025?",
    resolutionCriteria: "Resolves YES if any professional women's sports league (not tournament or one-off event) averages more than 10,000 fans per regular season game in their 2025 season. Source: league official attendance reports.",
    timeline: [
      { date: "Nov 2025", description: "NWSL reports 2025 regular season average attendance of 11,847 per game." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "NWSL's official average of 11,847 exceeds 10,000. NWSL is a professional women's league with a regular season. All criteria met cleanly.",
    alternateInterpretation: "None. Clear resolution.",
    marketPriceBehavior: "High at 75% from start given NWSL growth trends. Settled at 90% by mid-season.",
  },
  {
    id: "case-057",
    date: "2026-04-18",
    difficulty: 5,
    question: "Will a lab-grown meat product receive USDA approval and be sold in more than 100 US retail stores by end of 2025?",
    resolutionCriteria: "Resolves YES if a cell-cultivated meat product that has received USDA inspection approval is available for purchase in more than 100 retail store locations in the United States by December 31, 2025. Source: USDA FSIS approval records and company press release or SEC filing confirming retail distribution.",
    timeline: [
      { date: "Apr 2025", description: "Company E receives USDA approval for cultivated chicken product." },
      { date: "Aug 2025", description: "Company E announces retail launch in 85 Whole Foods locations." },
      { date: "Nov 2025", description: "Company E expands to 42 additional locations across other retailers, claiming 127 total retail points of sale." },
      { date: "Dec 2025", description: "Investigation reveals 18 of the claimed locations are food service establishments (restaurants), not retail stores." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "misresolved",
    correctFlaw: "definition_ambiguity",
    explanation: "The criteria specified 'retail store locations.' If 18 of the 127 claimed locations are restaurants (food service, not retail), the actual retail count is 109. This still exceeds 100. However, the resolution's reliance on the company's inflated claim of 127 without verifying the retail-versus-food-service distinction shows poor source verification. The result happens to be correct (109 > 100) but the methodology was flawed.",
    alternateInterpretation: "Since 109 retail locations still exceed 100, the YES resolution is actually correct even after removing food service locations. The resolution reached the right answer for somewhat wrong reasons.",
    marketPriceBehavior: "Started at 15%. Rose to 45% on USDA approval. Reached 65% on Whole Foods launch. Peaked at 78% on expansion news.",
  },
  {
    id: "case-058",
    date: "2026-04-19",
    difficulty: 4,
    question: "Will the global semiconductor market exceed $700 billion in revenue in 2025?",
    resolutionCriteria: "Resolves YES if total worldwide semiconductor revenue exceeds $700 billion for calendar year 2025, as reported by the World Semiconductor Trade Statistics (WSTS) organization. Source: WSTS year-end report or forecast.",
    timeline: [
      { date: "Feb 2026", description: "WSTS reports 2025 worldwide semiconductor revenue at $687 billion." },
      { date: "Mar 2026", description: "Gartner's separate analysis estimates $712 billion using a broader definition that includes certain MEMS and sensor products." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "The criteria specified WSTS as the source. WSTS reported $687 billion, which does not exceed $700 billion. Gartner's higher figure uses a different methodology and is not the specified source. Clean resolution using the stated source.",
    alternateInterpretation: "None. The source hierarchy is clear in the criteria.",
    marketPriceBehavior: "Started at 60%. Rose to 75% on strong AI chip demand. Settled at 55% as growth estimates moderated in Q4.",
  },
  {
    id: "case-059",
    date: "2026-04-20",
    difficulty: 3,
    question: "Will the Panama Canal fully restore normal transit capacity by mid-2025?",
    resolutionCriteria: "Resolves YES if the Panama Canal Authority restores daily transit slots to at least 36 (the pre-drought normal) by July 1, 2025. Source: Panama Canal Authority operational reports.",
    timeline: [
      { date: "May 2025", description: "Panama Canal Authority announces restoration of 34 daily transit slots." },
      { date: "Jun 2025", description: "Authority increases to 36 slots effective June 15, 2025." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "36 slots were restored by June 15, before the July 1 deadline. The source (PCA) matches. Clean resolution.",
    alternateInterpretation: "None.",
    marketPriceBehavior: "Gradually rose from 40% to 80% as water levels improved and slots increased.",
  },
  {
    id: "case-060",
    date: "2026-04-21",
    difficulty: 5,
    question: "Will a non-state actor successfully launch an object into Earth orbit in 2025?",
    resolutionCriteria: "Resolves YES if an entity that is not a national space agency or government-owned corporation successfully places an object into stable Earth orbit (at least one complete orbit) during 2025. Commercial companies that are publicly traded or privately held qualify as non-state actors. Source: NORAD tracking confirmation or official statement from launching entity with independent verification.",
    timeline: [
      { date: "Mar 2025", description: "SpaceX launches Starlink satellites into orbit." },
      { date: "May 2025", description: "Relativity Space launches its first commercial payload to orbit." },
      { date: "Jun 2025", description: "Debate: Is SpaceX a 'non-state actor' given significant US government contracts and NASA partnerships?" },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The criteria explicitly defined non-state actors as including 'commercial companies that are publicly traded or privately held.' SpaceX is a privately held commercial company. Government contracts don't make a company a government entity. Multiple qualifying launches occurred.",
    alternateInterpretation: "The criteria were unusually clear on this definition. The government-contractor question is interesting but was preemptively addressed by the criteria drafters.",
    marketPriceBehavior: "At 99% from day one. SpaceX and others launch regularly. Not a meaningful question.",
  },
  {
    id: "case-061",
    date: "2026-04-22",
    difficulty: 4,
    question: "Will Japan's Nikkei 225 close above 45,000 for the first time by end of 2025?",
    resolutionCriteria: "Resolves YES if the Nikkei 225 index closes above 45,000 on any trading day during 2025. Source: Tokyo Stock Exchange official closing data.",
    timeline: [
      { date: "Jul 2025", description: "Nikkei 225 reaches intraday high of 45,312 but closes at 44,890." },
      { date: "Oct 2025", description: "Nikkei 225 closes at 45,123." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "October closing of 45,123 exceeds 45,000. The criteria specified 'closes above,' and this was a closing price. The July intraday high doesn't count under 'closes above' but the October close does.",
    alternateInterpretation: "None. The distinction between intraday and closing prices is standard in financial markets.",
    marketPriceBehavior: "Traded around 50% early 2025. Rose to 70% as Nikkei approached 45K. Brief disappointment on July near-miss. Settled at 85% after October close.",
  },
  {
    id: "case-062",
    date: "2026-04-23",
    difficulty: 4,
    question: "Will voter turnout in the 2025 German federal election exceed 80%?",
    resolutionCriteria: "Resolves YES if official voter turnout in the 2025 German Bundestagswahl exceeds 80% of eligible voters. Source: Federal Returning Officer (Bundeswahlleiter) official results.",
    timeline: [
      { date: "Feb 2025", description: "German federal election held. Preliminary results show turnout of 82.4%." },
      { date: "Mar 2025", description: "Final official results from Bundeswahlleiter confirm turnout at 82.5% after counting overseas and postal ballots." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "82.5% exceeds 80%. Source is the Federal Returning Officer as specified. Clean resolution.",
    alternateInterpretation: "None.",
    marketPriceBehavior: "Traded around 55% before election. Historical average was 76%. Rose to 70% on high early voting reports. Jumped to 98% on preliminary results.",
  },
  {
    id: "case-063",
    date: "2026-04-24",
    difficulty: 5,
    question: "Will any pharmaceutical company begin Phase 3 trials for an aging reversal drug (targeting biological age reduction) by end of 2025?",
    resolutionCriteria: "Resolves YES if a Phase 3 clinical trial is registered on ClinicalTrials.gov with a primary endpoint of biological age reduction (measured by epigenetic clocks, telomere length, or equivalent validated biomarker) with a start date before January 1, 2026. Source: ClinicalTrials.gov registration.",
    timeline: [
      { date: "Sep 2025", description: "Company F registers Phase 3 trial with primary endpoint: 'Change in DNA methylation age (Horvath clock) from baseline.'" },
      { date: "Oct 2025", description: "Trial status shows 'Not yet recruiting' with estimated start date December 15, 2025." },
      { date: "Dec 2025", description: "Trial status updated to 'Recruiting' on December 20, 2025." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The trial is registered on ClinicalTrials.gov with a biological age primary endpoint and began recruiting before January 1, 2026. All criteria met. The transition from 'not yet recruiting' to 'recruiting' indicates the trial has started.",
    alternateInterpretation: "One could question whether DNA methylation age is a 'validated biomarker' for biological age, but the criteria listed 'epigenetic clocks' explicitly, and the Horvath clock is the most established epigenetic clock.",
    marketPriceBehavior: "Started at 10%. Jumped to 45% on trial registration. Rose to 75% when recruiting began.",
  },
];
