import { DailyCase } from "./types";

export const CASES_BATCH5: DailyCase[] = [
  {
    id: "case-084",
    date: "2026-05-15",
    difficulty: 4,
    question: "Will the global lithium price drop below $15,000 per tonne at any point in 2025?",
    resolutionCriteria: "Resolves YES if the Fastmarkets lithium carbonate (battery grade) CIF China, Japan & Korea spot price drops below $15,000/tonne at any point during 2025. Source: Fastmarkets price assessment.",
    timeline: [
      { date: "Mar 2025", description: "Lithium carbonate spot price hits $14,200/tonne amid oversupply." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "$14,200 < $15,000. Source matches. Clean resolution.",
    alternateInterpretation: "None.",
    marketPriceBehavior: "Started at 55%. Rose as lithium prices fell through Q1. Hit 90% when price broke $15K.",
  },
  {
    id: "case-085",
    date: "2026-05-16",
    difficulty: 5,
    question: "Will a decentralized autonomous organization (DAO) successfully acquire a publicly traded company by end of 2025?",
    resolutionCriteria: "Resolves YES if a DAO (defined as an organization governed by smart contracts with token-based voting and no single controlling entity) completes the acquisition of a publicly traded company (listed on a regulated stock exchange) by December 31, 2025. Source: SEC filings or equivalent regulatory filing and on-chain governance records.",
    timeline: [
      { date: "Jun 2025", description: "A DAO raises $400M through token sale to acquire Company H, listed on NASDAQ." },
      { date: "Aug 2025", description: "DAO governance votes to proceed. Acquisition structured through a Delaware LLC subsidiary controlled by the DAO's multisig." },
      { date: "Oct 2025", description: "SEC approves acquisition. Company H delisted. Ownership transferred to the LLC." },
      { date: "Nov 2025", description: "Legal scholars note the acquiring entity is technically a Delaware LLC, not the DAO itself. The DAO controls the LLC through a 5-of-9 multisig, which some argue means 9 individuals, not the DAO, are the true acquirers." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "indeterminate",
    explanation: "The criteria defined a DAO as having 'no single controlling entity.' A 5-of-9 multisig means 9 individuals control the entity. Whether this constitutes 'no single controlling entity' (technically 9 entities, not one) or violates the DAO's decentralization principle is genuinely debatable. The acquisition occurred through a traditional legal entity (LLC), not the DAO directly.",
    alternateInterpretation: "The multisig is a standard implementation detail for DAOs interfacing with traditional legal systems. The DAO's token holders voted to proceed, and the multisig executes their decision. This is the closest any DAO can get to a traditional acquisition given current legal frameworks.",
    marketPriceBehavior: "Rose from 5% to 40% on fundraise. Peaked at 65% on SEC approval. Debated at 50-60% on structural questions.",
  },
  {
    id: "case-086",
    date: "2026-05-17",
    difficulty: 3,
    question: "Will any player score 80+ points in a single NBA game in the 2024-25 season?",
    resolutionCriteria: "Resolves YES if any NBA player scores 80 or more points in a single regular season or playoff game during the 2024-25 NBA season. Source: NBA official box scores.",
    timeline: [
      { date: "Apr 2025", description: "No player exceeds 73 points in any game during the 2024-25 season." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "The season's highest individual scoring game was 73 points, below 80. Clean resolution.",
    alternateInterpretation: "None.",
    marketPriceBehavior: "Low at 8% most of season. Brief spikes on high-scoring nights. Never exceeded 15%.",
  },
  {
    id: "case-087",
    date: "2026-05-18",
    difficulty: 4,
    question: "Will more than 5 countries experience hyperinflation (>50% monthly inflation) in 2025?",
    resolutionCriteria: "Resolves YES if more than 5 sovereign nations experience monthly consumer price inflation exceeding 50% for at least one month during 2025. Source: IMF, World Bank, or Hanke-Krus hyperinflation database.",
    timeline: [
      { date: "Dec 2025", description: "Hanke-Krus database identifies 4 countries meeting the 50% monthly threshold in 2025: Venezuela, Zimbabwe, South Sudan, and Syria." },
      { date: "Dec 2025", description: "Two additional candidates (Lebanon and Argentina) had months approaching but not exceeding 50% monthly rate." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "4 countries met the threshold, not more than 5. Neither borderline case crossed 50% monthly. Clean resolution.",
    alternateInterpretation: "None. The count is clear and below the threshold.",
    marketPriceBehavior: "Traded at 20-30% through the year. Never seriously approached YES territory.",
  },
  {
    id: "case-088",
    date: "2026-05-19",
    difficulty: 5,
    question: "Will a major social media platform implement verified-identity-only posting by end of 2025?",
    resolutionCriteria: "Resolves YES if a social media platform with >50M MAU requires government ID verification as a mandatory condition for creating new accounts and posting content by December 31, 2025. Existing unverified accounts must be restricted from posting. Source: platform policy documentation and terms of service.",
    timeline: [
      { date: "Jul 2025", description: "Platform Z announces mandatory ID verification for all new accounts." },
      { date: "Sep 2025", description: "Policy implemented for new accounts. Existing unverified accounts can still post but see reduced distribution." },
      { date: "Nov 2025", description: "'Reduced distribution' means posts reach ~10% of normal audience, but users can still post." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "The criteria required existing unverified accounts to be 'restricted from posting.' Reduced distribution is not a posting restriction — users can still post, their content just reaches fewer people. The criteria distinguished between posting ability and content reach.",
    alternateInterpretation: "Reduced distribution to 10% of normal could be considered a de facto restriction from posting, as content effectively reaches almost no one. But the criteria used 'restricted from posting,' not 'restricted from reaching audiences.'",
    marketPriceBehavior: "Rose to 55% on announcement. Dropped to 30% when existing account policy was clarified. Settled at 15%.",
  },
  {
    id: "case-089",
    date: "2026-05-20",
    difficulty: 4,
    question: "Will the global number of refugees exceed 120 million by end of 2025?",
    resolutionCriteria: "Resolves YES if UNHCR's year-end report shows total forcibly displaced people (refugees, asylum seekers, and internally displaced persons) exceeding 120 million for 2025. Source: UNHCR Global Trends report.",
    timeline: [
      { date: "Jun 2026", description: "UNHCR Global Trends reports 127.3 million forcibly displaced people at end of 2025." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "127.3M > 120M. Source matches. The criteria included IDPs in the count, matching UNHCR's methodology. Clean resolution.",
    alternateInterpretation: "Some might distinguish between 'refugees' (in the title) and 'forcibly displaced people' (in the criteria), but the criteria explicitly defined the scope to include IDPs and asylum seekers.",
    marketPriceBehavior: "High at 75% given upward trend. Gradually rose to 88% through the year.",
  },
  {
    id: "case-090",
    date: "2026-05-21",
    difficulty: 3,
    question: "Will any country's women's soccer team win a FIFA tournament match by more than 10 goals in 2025?",
    resolutionCriteria: "Resolves YES if any women's national soccer team wins a FIFA-sanctioned tournament match (World Cup qualifiers, regional championships) by a margin of 11+ goals during 2025. Source: FIFA official match records.",
    timeline: [
      { date: "Apr 2025", description: "In World Cup qualifying, Team A defeats Team B 13-0." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "13-goal margin exceeds 10. FIFA official match in qualifying. Clean resolution.",
    alternateInterpretation: "None.",
    marketPriceBehavior: "Moderate at 55% — large margins happen occasionally in women's qualifying. Rose to 99% after the match.",
  },
  {
    id: "case-091",
    date: "2026-05-22",
    difficulty: 5,
    question: "Will a major earthquake (M8.0+) trigger a tsunami warning for the entire Pacific basin in 2025?",
    resolutionCriteria: "Resolves YES if the Pacific Tsunami Warning Center (PTWC) issues a tsunami warning covering the entire Pacific basin (not just regional) following an M8.0+ earthquake during 2025. Source: PTWC official warning bulletins.",
    timeline: [
      { date: "Aug 2025", description: "M8.2 earthquake strikes off the coast of Chile." },
      { date: "Aug 2025", description: "PTWC issues tsunami warning for South America Pacific coast and Hawaii. Advisory (not warning) for rest of Pacific." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "The criteria specified a warning 'covering the entire Pacific basin.' PTWC issued a warning for portions of the Pacific and advisories for the rest. An advisory is a lower alert level than a warning. The 'entire Pacific basin' warning condition was not met.",
    alternateInterpretation: "The PTWC did issue alerts for the entire Pacific, but the criteria specifically required 'warning' level, not 'advisory.' These are distinct alert levels in PTWC's system.",
    marketPriceBehavior: "Brief spike to 45% on earthquake. Quickly settled to 20% when partial warning coverage was confirmed.",
  },
  {
    id: "case-092",
    date: "2026-05-23",
    difficulty: 4,
    question: "Will any autonomous drone delivery service complete more than 1 million deliveries in a single country in 2025?",
    resolutionCriteria: "Resolves YES if any autonomous drone delivery service (fully autonomous, not remotely piloted) completes over 1 million commercial deliveries within a single country during calendar year 2025. Source: company filings, aviation authority records, or credible third-party audit.",
    timeline: [
      { date: "Jan 2026", description: "Meituan reports 1.2 million drone deliveries in China for 2025. However, Meituan's drones operate semi-autonomously with remote pilot oversight for each flight." },
      { date: "Feb 2026", description: "Wing (Alphabet) reports 850,000 deliveries in Australia with fully autonomous operations." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "The criteria specified 'fully autonomous, not remotely piloted.' Meituan's 1.2M deliveries used semi-autonomous drones with remote pilot oversight, disqualifying them. Wing's fully autonomous deliveries totaled 850,000, below 1 million. No service met both the autonomy and volume requirements simultaneously.",
    alternateInterpretation: "The level of remote oversight in Meituan's operations could be debated — oversight doesn't necessarily mean piloting. But the criteria drew a clear line at 'fully autonomous.'",
    marketPriceBehavior: "Rose to 55% on Meituan volume reports. Dropped to 30% when autonomy level was clarified. Wing's numbers kept it at 25%.",
  },
  {
    id: "case-093",
    date: "2026-05-24",
    difficulty: 3,
    question: "Will the global box office exceed $35 billion in 2025?",
    resolutionCriteria: "Resolves YES if total worldwide theatrical box office revenue exceeds $35 billion for calendar year 2025. Source: Comscore or Motion Picture Association (MPA) annual report.",
    timeline: [
      { date: "Jan 2026", description: "Comscore reports 2025 global box office at $36.8 billion." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "$36.8B > $35B. Source matches. Clean resolution.",
    alternateInterpretation: "None.",
    marketPriceBehavior: "Started at 55%. Rose through strong summer season. Settled at 85% after Q3 data.",
  },
  {
    id: "case-094",
    date: "2026-05-25",
    difficulty: 5,
    question: "Will a verifiable zero-knowledge proof system be deployed for a national election in 2025?",
    resolutionCriteria: "Resolves YES if any country deploys a zero-knowledge proof system as part of its official national election process (vote casting, counting, or verification) in 2025. 'Deployed' means used in the actual election, not a pilot or demonstration. Source: election commission official report or independent election monitor certification.",
    timeline: [
      { date: "May 2025", description: "Country J uses a ZK-proof based system for voter eligibility verification in its parliamentary election." },
      { date: "Jun 2025", description: "System used only for eligibility checking, not vote casting or counting. Traditional paper ballots used for actual voting." },
      { date: "Jul 2025", description: "International observers confirm ZK-proof system was used for eligibility verification in 40% of polling stations." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The criteria specified 'vote casting, counting, or verification.' Voter eligibility verification is part of the election verification process. The system was used in the actual election (not a pilot) in 40% of polling stations. All criteria met.",
    alternateInterpretation: "One could argue 'verification' in the criteria means vote verification (confirming votes were correctly counted), not voter eligibility verification. But the criteria didn't restrict the type of verification.",
    marketPriceBehavior: "Very low at 5% most of year. Jumped to 50% on Country J announcement. Rose to 70% after observer confirmation.",
  },
  {
    id: "case-095",
    date: "2026-05-26",
    difficulty: 4,
    question: "Will the Thames Barrier be closed more than 10 times in the 2024-25 flood season?",
    resolutionCriteria: "Resolves YES if the Thames Barrier is closed for flood defense purposes more than 10 times during the 2024-25 flood season (October 2024 - March 2025). Source: UK Environment Agency Thames Barrier closure records.",
    timeline: [
      { date: "Apr 2025", description: "Environment Agency reports 14 flood defense closures during the 2024-25 season." },
      { date: "Apr 2025", description: "Two of the 14 closures were for 'maintenance and testing' rather than active flood defense." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The criteria specified closures 'for flood defense purposes.' Excluding 2 maintenance closures, 12 flood defense closures occurred. 12 > 10. Even under the stricter interpretation, the threshold is met.",
    alternateInterpretation: "If all 14 closures counted, the margin is even larger. Either way, the threshold is exceeded.",
    marketPriceBehavior: "Started at 35%. Rose through wet autumn. Reached 75% by February after several storm surges.",
  },
  {
    id: "case-096",
    date: "2026-05-27",
    difficulty: 5,
    question: "Will a large language model pass the Turing Test in a controlled, peer-reviewed experiment by end of 2025?",
    resolutionCriteria: "Resolves YES if a peer-reviewed paper published by December 31, 2025 demonstrates an LLM passing the Turing Test in a controlled experiment where human judges cannot distinguish the AI from humans at a rate statistically significant above chance (p<0.05, minimum 30 judges, minimum 5-minute conversations). Source: peer-reviewed publication.",
    timeline: [
      { date: "Sep 2025", description: "Paper published: LLM fooled 54% of 100 judges in 5-minute text conversations. Random chance = 50%." },
      { date: "Oct 2025", description: "Statistical analysis: p=0.04, technically meeting the p<0.05 threshold." },
      { date: "Nov 2025", description: "Critics argue 54% with p=0.04 represents marginal statistical significance and that the Turing Test was never meant to be passed at barely-above-chance rates." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The criteria set specific quantitative thresholds: p<0.05, minimum 30 judges, minimum 5-minute conversations. All were met (p=0.04, 100 judges, 5-minute conversations). The philosophical debate about what constitutes 'passing' the Turing Test is irrelevant — the criteria operationalized the test with specific statistical parameters that were satisfied.",
    alternateInterpretation: "A 54% rate barely above chance raises questions about whether this is meaningfully 'passing' the test. The criteria's statistical threshold may have been set too low, but the resolution correctly applied the stated criteria.",
    marketPriceBehavior: "Started at 25%. Rose to 55% on paper publication. Debated between 45-65% on significance interpretation. Resolved YES at 60%.",
  },
  {
    id: "case-097",
    date: "2026-05-28",
    difficulty: 3,
    question: "Will any passenger airline operate a flight using 100% sustainable aviation fuel (SAF) in 2025?",
    resolutionCriteria: "Resolves YES if a scheduled commercial passenger airline operates at least one revenue flight using 100% sustainable aviation fuel (no conventional jet fuel blend) during 2025. Source: airline press release confirmed by fuel supplier documentation.",
    timeline: [
      { date: "Jun 2025", description: "Airline operates demonstration flight using 100% SAF between London and New York." },
      { date: "Jun 2025", description: "Flight carried paying passengers on a regularly scheduled route." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The flight used 100% SAF, carried revenue passengers, and operated on a scheduled route. Both airline and fuel supplier confirmed. All criteria met.",
    alternateInterpretation: "Some might question whether a single flight constitutes meaningful SAF deployment, but the criteria only required 'at least one revenue flight.'",
    marketPriceBehavior: "Started at 40%. Rose to 70% as airline announced plans. Settled at 90% after successful flight.",
  },
  {
    id: "case-098",
    date: "2026-05-29",
    difficulty: 4,
    question: "Will any African nation qualify for the knockout stage of a FIFA World Cup (men's or women's) held in 2025?",
    resolutionCriteria: "Resolves YES if any African Football Confederation (CAF) member nation qualifies for the knockout round (Round of 16 or equivalent) of any FIFA World Cup tournament (men's or women's) held during 2025. Source: FIFA official tournament results.",
    timeline: [
      { date: "2025", description: "No FIFA World Cup (men's or women's) is held in 2025. The men's tournament is in 2026, women's in 2027." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "No FIFA World Cup was held in 2025. The criteria cannot be met when the prerequisite event doesn't occur. However, the question itself was poorly constructed — it asked about an event that couldn't happen in the specified year.",
    alternateInterpretation: "The FIFA Club World Cup was held in 2025, but it features clubs, not nations, and isn't the 'FIFA World Cup' referenced in the criteria.",
    marketPriceBehavior: "Should have been near 0% from the start. Briefly traded at 10-15% by uninformed participants before settling at 2%.",
  },
  {
    id: "case-099",
    date: "2026-05-30",
    difficulty: 5,
    question: "Will any government implement a universal basic income program (unconditional, covering >50% of adult population) by end of 2025?",
    resolutionCriteria: "Resolves YES if any sovereign nation implements a cash transfer program that is unconditional (no work requirements, means testing, or behavioral conditions), covers more than 50% of the adult population, and provides payments for at least 6 consecutive months during 2025. Source: government policy documentation or World Bank program database.",
    timeline: [
      { date: "Mar 2025", description: "Country K launches 'Citizen's Dividend' program providing monthly payments to all citizens over 18." },
      { date: "Jun 2025", description: "Program reaches 65% of adult population. However, citizens must register and provide bank account information — approximately 35% of eligible adults have not registered." },
      { date: "Sep 2025", description: "Analysts debate whether registration requirement makes the program 'conditional' since non-registered citizens are excluded." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "Registration is an administrative requirement for payment delivery, not a behavioral condition. The criteria specified 'no work requirements, means testing, or behavioral conditions.' Registering for a government benefit is not a behavioral condition — it's a practical necessity for cash transfer programs. 65% coverage exceeds the 50% threshold. Payments ran for 6+ months.",
    alternateInterpretation: "If registration effectively excludes marginalized populations who lack bank accounts or documentation, the program may not be truly 'unconditional' in practice. But the criteria defined conditionality narrowly (work, means, behavior).",
    marketPriceBehavior: "Rose from 10% to 45% on program announcement. Debated between 40-60% on registration question. Settled at 55%.",
  },
  {
    id: "case-100",
    date: "2026-05-31",
    difficulty: 4,
    question: "Will the total value locked (TVL) in DeFi protocols exceed $500 billion by end of 2025?",
    resolutionCriteria: "Resolves YES if total value locked across all decentralized finance protocols exceeds $500 billion on any day before January 1, 2026. Source: DefiLlama aggregate TVL data.",
    timeline: [
      { date: "Nov 2025", description: "DefiLlama shows aggregate TVL reaching $512 billion." },
      { date: "Nov 2025", description: "Analysis reveals $45 billion of the TVL comes from 'liquid staking' protocols where the same ETH is counted in both the staking protocol and derivative DeFi positions." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The criteria specified DefiLlama as the source. DefiLlama's methodology includes liquid staking in its aggregate TVL. Double-counting concerns relate to DefiLlama's methodology, not to the resolution criteria. The criteria accepted DefiLlama's number without requiring methodology adjustments. Even excluding the double-counted amount ($512B - $45B = $467B), the headline DefiLlama figure is the specified source.",
    alternateInterpretation: "Using the source's methodology as-is is correct when the criteria specify the source. Debates about methodology are relevant to the source's credibility but not to the resolution under these criteria.",
    marketPriceBehavior: "Rose from 35% to 65% through DeFi growth cycle. Jumped to 90% on crossing $500B.",
  },
  {
    id: "case-101",
    date: "2026-06-01",
    difficulty: 5,
    question: "Will a synthetic biology organism designed for carbon capture be deployed in an ocean environment at scale by end of 2025?",
    resolutionCriteria: "Resolves YES if an engineered organism designed primarily for atmospheric CO2 capture is deliberately released into an ocean environment covering more than 1 square kilometer, with regulatory approval, by December 31, 2025. Source: regulatory approval documentation and peer-reviewed deployment report.",
    timeline: [
      { date: "Aug 2025", description: "Biotech company receives regulatory approval from Pacific island nation to deploy engineered cyanobacteria in a 2.5 km² ocean area." },
      { date: "Sep 2025", description: "Deployment begins. Engineered organisms released into contained open-ocean pens covering 1.8 km²." },
      { date: "Oct 2025", description: "Environmental groups challenge whether 'contained open-ocean pens' constitute deployment 'in an ocean environment' or are essentially large aquaculture installations." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "indeterminate",
    explanation: "The criteria said 'released into an ocean environment.' Contained pens in the ocean are technically in the ocean environment but are not an uncontained open-ocean release. Whether pens constitute deployment 'in' the ocean environment depends on whether the containment negates the 'in the ocean' nature of the deployment. The organisms are physically in the ocean, separated by permeable membranes.",
    alternateInterpretation: "The pens are in the ocean, using ocean water, exposed to ocean conditions. The containment is for regulatory compliance, not a fundamental change in environment. The organisms are functionally deployed in the ocean.",
    marketPriceBehavior: "Very low at 3% most of year. Jumped to 35% on regulatory approval. Rose to 50% on deployment. Debated at 40-55%.",
  },
  {
    id: "case-102",
    date: "2026-06-02",
    difficulty: 3,
    question: "Will any spacecraft land on the far side of the Moon in 2025 (excluding Chinese missions)?",
    resolutionCriteria: "Resolves YES if any spacecraft operated by a space agency or company other than CNSA (China National Space Administration) achieves a soft landing on the far side of the Moon during 2025. Source: operating entity's official confirmation and independent tracking verification.",
    timeline: [
      { date: "2025", description: "No non-Chinese spacecraft attempts a far-side lunar landing in 2025." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "No qualifying mission attempted the task. Clean resolution by non-occurrence.",
    alternateInterpretation: "None.",
    marketPriceBehavior: "Low at 10% all year. No scheduled missions made this plausible.",
  },
  {
    id: "case-103",
    date: "2026-06-03",
    difficulty: 4,
    question: "Will the average global internet speed exceed 150 Mbps by end of 2025?",
    resolutionCriteria: "Resolves YES if the global average fixed broadband download speed exceeds 150 Mbps for Q4 2025. Source: Ookla Speedtest Global Index.",
    timeline: [
      { date: "Jan 2026", description: "Ookla reports Q4 2025 global average fixed broadband download speed at 142.3 Mbps." },
      { date: "Jan 2026", description: "Ookla notes methodology change in Q3 2025 that excluded speed tests from connections under 5 Mbps, increasing the average." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "142.3 Mbps does not exceed 150 Mbps. Despite the methodology change that increased the average, it still falls short. The criteria specified Ookla as the source, and Ookla's reported figure is below threshold.",
    alternateInterpretation: "Under the old methodology, the average would have been even lower. The methodology change actually favored a YES resolution but still wasn't enough.",
    marketPriceBehavior: "Traded at 35-45% through the year. Slight boost on methodology change but never approached 150 Mbps.",
  },
  {
    id: "case-104",
    date: "2026-06-04",
    difficulty: 5,
    question: "Will a court rule that training AI on copyrighted data without permission constitutes fair use by end of 2025?",
    resolutionCriteria: "Resolves YES if a federal court (district or higher) in the United States issues a ruling that using copyrighted works for AI training purposes constitutes fair use under 17 U.S.C. § 107, in a final judgment (not preliminary ruling) by December 31, 2025. Source: court opinion published on PACER or court website.",
    timeline: [
      { date: "Jul 2025", description: "District court issues summary judgment in favor of AI company: 'The use of copyrighted works for training machine learning models is transformative and constitutes fair use.'" },
      { date: "Aug 2025", description: "Ruling applies specifically to text-based training data. Court explicitly declines to address image, music, or code training." },
      { date: "Sep 2025", description: "Plaintiffs appeal. District court judgment stands pending appeal." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The criteria required a federal court final judgment ruling AI training as fair use. A summary judgment is a final judgment at the district court level. The pending appeal doesn't negate the issued judgment. The criteria specified 'district or higher,' and the district court ruling satisfies this. The narrow scope (text only) doesn't matter — the criteria didn't require a ruling covering all types of copyrighted works.",
    alternateInterpretation: "A district court ruling with a pending appeal could be seen as not truly 'final' in the broader legal sense. But in legal terminology, a summary judgment is a final judgment at that court level.",
    marketPriceBehavior: "Started at 35%. Rose to 60% as trial progressed. Jumped to 82% on ruling. Slight dip on narrow scope but held at 75%.",
  },
  {
    id: "case-105",
    date: "2026-06-05",
    difficulty: 4,
    question: "Will any European football club be sold for more than €5 billion in 2025?",
    resolutionCriteria: "Resolves YES if a European football club changes ownership in a transaction valued at more than €5 billion (including debt assumption) during 2025. Source: official club announcement or regulatory filing.",
    timeline: [
      { date: "Jun 2025", description: "Premier League club sold. Transaction announced at £4.8 billion (approximately €5.6 billion at time of announcement)." },
      { date: "Jul 2025", description: "Of the £4.8B, £2.1B is equity purchase and £2.7B is assumed debt and committed future investment." },
      { date: "Aug 2025", description: "Analysts debate whether 'committed future investment' should be included in transaction value or only purchase price and assumed debt." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The criteria specified transaction value 'including debt assumption.' Even excluding committed future investment (£2.1B equity + £2.7B debt = £4.8B = ~€5.6B), the threshold is exceeded. The debate about future investment is moot since equity plus debt alone crosses €5B.",
    alternateInterpretation: "If only the equity purchase price (£2.1B ≈ €2.5B) counted, the threshold wouldn't be met. But the criteria explicitly included debt assumption.",
    marketPriceBehavior: "Moderate at 30% given few clubs of that value. Jumped to 80% on sale announcement. Brief debate on valuation methodology.",
  },
  {
    id: "case-106",
    date: "2026-06-06",
    difficulty: 3,
    question: "Will global renewable energy generation exceed fossil fuel generation for any single month in 2025?",
    resolutionCriteria: "Resolves YES if total global electricity generation from renewable sources (solar, wind, hydro, geothermal, biomass) exceeds total generation from fossil fuels (coal, natural gas, oil) for any calendar month in 2025. Source: Ember Global Electricity Review or IEA monthly data.",
    timeline: [
      { date: "2025", description: "Renewable generation approaches but does not exceed fossil fuel generation in any month. Closest month was May 2025 at 48.2% renewable." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "Renewables did not exceed fossil fuels in any month. 48.2% is the closest approach but below 50%. Clean resolution.",
    alternateInterpretation: "None. The data is clear.",
    marketPriceBehavior: "Started at 25%. Rose to 40% during spring (high hydro/solar months). Settled at 20% when no month crossed 50%.",
  },
  {
    id: "case-107",
    date: "2026-06-07",
    difficulty: 5,
    question: "Will evidence of liquid water be confirmed on Mars (not ice, not ancient water) by end of 2025?",
    resolutionCriteria: "Resolves YES if NASA, ESA, or a peer-reviewed publication confirms the current existence of stable liquid water on Mars (not subsurface ice, not evidence of past water) by December 31, 2025. 'Confirms' means the agency or paper states the finding as established fact, not hypothesis. Source: space agency press release or peer-reviewed paper in a journal with IF > 10.",
    timeline: [
      { date: "May 2025", description: "ESA's Mars Express publishes new radar data consistent with subsurface liquid water bodies." },
      { date: "Jun 2025", description: "Paper in Science states: 'Radar reflections are best explained by liquid water, though high-concentration brine or certain mineral compositions cannot be excluded.'" },
      { date: "Jul 2025", description: "NASA states it considers the evidence 'strongly suggestive but not definitive.'" },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "The criteria required findings stated as 'established fact, not hypothesis.' Both the paper ('cannot be excluded' alternative explanations) and NASA ('strongly suggestive but not definitive') used hedged language. No source presented liquid water as confirmed fact.",
    alternateInterpretation: "The Science paper does say liquid water is the 'best explanation,' which approaches but doesn't reach the 'established fact' standard required by the criteria.",
    marketPriceBehavior: "Jumped to 45% on radar data. Settled at 25% after hedged language was analyzed.",
  },
];
