import { DailyCase } from "./types";

export const CASES_BATCH1: DailyCase[] = [
  {
    id: "case-008",
    date: "2026-02-28",
    difficulty: 4,
    question: "Will the US Supreme Court overturn or substantially narrow Chevron deference by June 30, 2025?",
    resolutionCriteria: "Resolves YES if the Supreme Court issues a ruling that explicitly overturns Chevron v. Natural Resources Defense Council (1984) or narrows it such that courts are no longer required to defer to agency interpretations of ambiguous statutes. Source: official Supreme Court opinion.",
    timeline: [
      { date: "Jan 2025", description: "Supreme Court hears oral arguments in Loper Bright Enterprises v. Raimondo." },
      { date: "Jun 2025", description: "Court issues 6-3 opinion stating Chevron is 'overruled' but preserves prior rulings made under Chevron as stare decisis." },
      { date: "Jun 2025", description: "Dissent argues the majority only nominally overruled Chevron while preserving its practical effects through stare decisis carve-out." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "indeterminate",
    explanation: "The Court used the word 'overruled' but simultaneously preserved all prior Chevron-based rulings. Whether this constitutes 'substantially narrowing' versus 'overturning' is debatable, and whether the stare decisis preservation negates the practical impact creates genuine indeterminacy about whether the criteria were met in substance.",
    alternateInterpretation: "The opinion explicitly says 'Chevron is overruled.' The plain text of the ruling satisfies the criteria regardless of practical downstream effects.",
    marketPriceBehavior: "Rose from 65% to 92% after oral arguments. Briefly dipped to 80% on rumors of narrow ruling. Jumped to 98% on decision day.",
  },
  {
    id: "case-009",
    date: "2026-03-01",
    difficulty: 5,
    question: "Will China's GDP growth rate for Q3 2025 exceed 5.0% year-over-year as reported by the National Bureau of Statistics?",
    resolutionCriteria: "Resolves YES if China's NBS reports Q3 2025 real GDP growth exceeding 5.0% YoY in their initial release. 'Initial release' means the first official publication, not subsequent revisions.",
    timeline: [
      { date: "Oct 2025", description: "NBS publishes Q3 GDP growth at 5.1% YoY in initial release." },
      { date: "Nov 2025", description: "Independent economists using alternative indicators estimate actual growth at 3.2-3.8%." },
      { date: "Dec 2025", description: "NBS revises Q3 figure to 4.8% in annual GDP revision." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The criteria explicitly specified 'initial release' from NBS, which showed 5.1%. The revision and independent estimates are irrelevant under the stated criteria. The resolution correctly applied the rules as written.",
    alternateInterpretation: "One could argue that using data widely considered unreliable undermines the spirit of the question, but the criteria were explicit about using the NBS initial release.",
    marketPriceBehavior: "Stable around 70% most of the quarter. Brief spike to 85% on positive PMI data. Settled at 78% before release.",
  },
  {
    id: "case-010",
    date: "2026-03-02",
    difficulty: 4,
    question: "Will the FDA approve a CRISPR-based therapy for sickle cell disease before July 1, 2025?",
    resolutionCriteria: "Resolves YES if the FDA grants full approval (not accelerated approval, not Emergency Use Authorization) to any CRISPR-based gene therapy for sickle cell disease before July 1, 2025. Source: FDA press release or Federal Register.",
    timeline: [
      { date: "Dec 2024", description: "FDA grants accelerated approval to Casgevy (exagamglogene autotemcel) for sickle cell disease." },
      { date: "Mar 2025", description: "Vertex submits supplemental BLA for full approval based on confirmatory trial data." },
      { date: "Jun 2025", description: "FDA converts accelerated approval to full approval on June 28, 2025." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "misresolved",
    correctFlaw: "procedural_substantive_confusion",
    explanation: "The original accelerated approval in December 2024 was explicitly excluded by the criteria. The June 2025 action was a conversion from accelerated to full approval, not an original full approval grant. Whether a conversion constitutes 'granting full approval' is a procedural question — the FDA's action was procedurally converting a prior approval type, not issuing a new approval.",
    alternateInterpretation: "The FDA's own press release for the conversion used the phrase 'grants full approval.' The end state is that the drug has full approval status, which arguably satisfies the criteria.",
    marketPriceBehavior: "Dropped from 60% to 25% after accelerated-only approval in Dec 2024. Rose to 55% on supplemental filing. Jumped to 88% on conversion.",
  },
  {
    id: "case-011",
    date: "2026-03-03",
    difficulty: 3,
    question: "Will more than 50 countries sign the Global AI Safety Treaty by December 31, 2025?",
    resolutionCriteria: "Resolves YES if 51 or more sovereign nations have signed the Global AI Safety Treaty text by end of 2025. 'Signed' means official signature by authorized representative, not ratification. Source: UN Treaty Collection or treaty secretariat official count.",
    timeline: [
      { date: "Sep 2025", description: "Treaty opened for signature at UN General Assembly. 38 countries sign on opening day." },
      { date: "Nov 2025", description: "12 additional countries sign, bringing total to 50." },
      { date: "Dec 29, 2025", description: "Taiwan signs the treaty through its representative." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "indeterminate",
    explanation: "Taiwan's status as a 'sovereign nation' is contested internationally. The UN Treaty Collection does not list Taiwan as a member state. If Taiwan counts, the total is 51 (YES). If it doesn't, the total is 50 (NO). The criteria specified 'sovereign nations' without defining how sovereignty disputes should be handled.",
    alternateInterpretation: "The UN Treaty Collection is the specified source, and Taiwan cannot sign UN treaties. Under the specified source, the count is 50, and NO is correct.",
    marketPriceBehavior: "Rose steadily from 30% to 65% after opening day surge. Plateaued at 58% through November. Chaotic trading after Taiwan announcement.",
  },
  {
    id: "case-012",
    date: "2026-03-04",
    difficulty: 5,
    question: "Will a commercially available quantum computer demonstrate quantum advantage on a practical optimization problem by end of 2025?",
    resolutionCriteria: "Resolves YES if a peer-reviewed paper published in a journal with impact factor > 10 demonstrates that a commercially available quantum computer solves a practical optimization problem faster than the best known classical algorithm on the best available classical hardware. Must be published (not just preprint) by December 31, 2025.",
    timeline: [
      { date: "Aug 2025", description: "IBM publishes paper in Nature showing 127-qubit system solving supply chain optimization 12x faster than classical benchmark." },
      { date: "Sep 2025", description: "Google team publishes response showing a new classical algorithm that matches IBM's quantum result." },
      { date: "Oct 2025", description: "IBM authors publish addendum arguing Google's algorithm was not 'known' at time of original submission." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "misresolved",
    correctFlaw: "retroactive_reinterpretation",
    explanation: "The criteria state 'best known classical algorithm.' By the time of resolution, Google's classical algorithm was known and matched quantum performance. The resolution used the state of knowledge at paper submission rather than at resolution time, but 'best known' should logically refer to the state of knowledge at resolution.",
    alternateInterpretation: "The peer-reviewed paper demonstrated the advantage at time of publication. Subsequent classical improvements don't retroactively invalidate published results. The criteria asked about a published demonstration, not an ongoing superiority.",
    marketPriceBehavior: "Jumped to 82% on IBM paper. Crashed to 35% on Google response. Recovered to 60% on IBM addendum. Controversial resolution at 75%.",
  },
  {
    id: "case-013",
    date: "2026-03-05",
    difficulty: 3,
    question: "Will Tesla deliver more than 500,000 vehicles in Q4 2025?",
    resolutionCriteria: "Resolves YES if Tesla's official Q4 2025 delivery report shows total deliveries exceeding 500,000 units. Source: Tesla's investor relations press release.",
    timeline: [
      { date: "Jan 2026", description: "Tesla IR publishes Q4 2025 delivery report: 512,340 total deliveries." },
      { date: "Jan 2026", description: "Report includes footnote: '~8,200 units delivered to internal fleet programs are included in delivery totals.'" },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "Tesla's official report shows 512,340 deliveries, exceeding 500,000. The criteria specified Tesla's IR press release as the source, and the number clearly exceeds the threshold. Internal fleet deliveries are included in Tesla's standard delivery reporting methodology.",
    alternateInterpretation: "If internal fleet deliveries were excluded, the count would be ~504,140, still above 500,000. Even under the most restrictive interpretation, the threshold is met.",
    marketPriceBehavior: "Traded between 55-70% through the quarter. Rose to 85% after strong October numbers. Settled at 92% before report.",
  },
  {
    id: "case-014",
    date: "2026-03-06",
    difficulty: 4,
    question: "Will the UK officially rejoin any EU institution or program by December 31, 2025?",
    resolutionCriteria: "Resolves YES if the United Kingdom formally rejoins any EU institution, agency, or funded program (e.g., Erasmus+, Horizon Europe, Europol) through an official agreement signed by both parties. Source: official UK government or European Commission announcement.",
    timeline: [
      { date: "May 2025", description: "UK and EU announce 'association agreement' for Horizon Europe participation." },
      { date: "Jul 2025", description: "Agreement signed. UK gains associate country status, contributing financially and participating in grants." },
      { date: "Aug 2025", description: "Legal analysts note associate status is not 'rejoining' — it's a new third-country participation framework distinct from prior membership." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "misresolved",
    correctFlaw: "definition_ambiguity",
    explanation: "The criteria used 'rejoin' which implies returning to prior membership status. Associate country status in Horizon Europe is a different legal framework than the UK's previous membership-based participation. The UK did not 'rejoin' — it joined under a new, lesser arrangement. The resolution conflated 'participation' with 'rejoining.'",
    alternateInterpretation: "The spirit of the question was whether the UK would resume participation in EU programs. The Horizon Europe association achieves this practically, even if the legal framework differs from prior membership.",
    marketPriceBehavior: "Low at 15% through early 2025. Jumped to 55% on negotiation news. Rose to 78% on agreement signing. Debate on 'rejoining' semantics kept it volatile.",
  },
  {
    id: "case-015",
    date: "2026-03-07",
    difficulty: 5,
    question: "Will any major social media platform with >100M MAU permanently ban political advertising globally by end of 2025?",
    resolutionCriteria: "Resolves YES if a social media platform with over 100 million monthly active users announces and implements a permanent, global ban on all political advertising by December 31, 2025. 'Political advertising' defined as paid content promoting candidates, parties, or ballot measures. Source: official company blog post or SEC filing.",
    timeline: [
      { date: "Jun 2025", description: "Platform Y announces 'permanent ban on political ads globally' via blog post." },
      { date: "Jul 2025", description: "Implementation reveals exemptions: issue-based advocacy ads without candidate mentions are still permitted." },
      { date: "Sep 2025", description: "Investigative report finds political PACs running 'issue ads' that are effectively candidate promotion." },
      { date: "Nov 2025", description: "Platform Y quietly introduces 'election integrity ads' category allowing government-sponsored civic engagement content." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "misresolved",
    correctFlaw: "procedural_substantive_confusion",
    explanation: "The platform announced a ban (procedural) but the implementation contained exemptions that allowed political advertising to continue in substance through issue ads and the new civic engagement category. The criteria required the ban to be 'implemented,' but implementation with these carve-outs doesn't constitute a true ban on 'all political advertising.'",
    alternateInterpretation: "The criteria defined political advertising as 'paid content promoting candidates, parties, or ballot measures.' Issue advocacy without candidate mentions arguably falls outside this definition, making the ban technically complete within the specified scope.",
    marketPriceBehavior: "Surged to 90% on announcement. Dropped to 65% as exemptions emerged. Settled at 58% amid debate about what counts as implementation.",
  },
  {
    id: "case-016",
    date: "2026-03-08",
    difficulty: 4,
    question: "Will the James Webb Space Telescope discover definitive evidence of biosignatures in an exoplanet atmosphere by end of 2025?",
    resolutionCriteria: "Resolves YES if NASA or ESA officially announces that JWST data provides definitive evidence of biological origin atmospheric signatures on an exoplanet. 'Definitive' means the announcing agency uses language indicating certainty rather than possibility. Source: NASA/ESA press release.",
    timeline: [
      { date: "Apr 2025", description: "JWST detects dimethyl sulfide (DMS) and phosphine in atmosphere of K2-18b at statistically significant levels." },
      { date: "May 2025", description: "NASA press release states: 'Strong evidence of molecules associated with biological processes detected in K2-18b atmosphere.'" },
      { date: "Jun 2025", description: "Peer review debates whether DMS can be produced abiotically under K2-18b's conditions." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "NASA's language used 'associated with biological processes' rather than definitive language. The criteria required the agency to use language 'indicating certainty rather than possibility.' 'Associated with' is correlative language, not definitive. The NO resolution correctly applied the linguistic standard in the criteria.",
    alternateInterpretation: "The detection itself could be considered definitive evidence even if the press release was cautiously worded, as scientific communication traditionally hedges certainty. But the criteria specified the language of the announcement, not the underlying science.",
    marketPriceBehavior: "Spiked to 72% on detection news. Dropped to 40% when press release language was analyzed. Settled at 25% before resolution.",
  },
  {
    id: "case-017",
    date: "2026-03-09",
    difficulty: 3,
    question: "Will India's Chandrayaan-4 mission successfully collect and return lunar samples to Earth before 2026?",
    resolutionCriteria: "Resolves YES if ISRO's Chandrayaan-4 mission returns lunar surface samples to Earth before January 1, 2026. 'Successfully' means samples are recovered intact on Earth. Source: ISRO official communication.",
    timeline: [
      { date: "Mar 2025", description: "Chandrayaan-4 launches successfully." },
      { date: "Jun 2025", description: "Spacecraft enters lunar orbit and deploys sample collection module." },
      { date: "Oct 2025", description: "ISRO announces sample collection successful; return vehicle launched from lunar surface." },
      { date: "Dec 2025", description: "Return capsule delayed due to trajectory correction. New ETA: January 3, 2026." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "The return capsule did not arrive before January 1, 2026. Despite successful collection, the criteria required Earth return before 2026. The three-day delay clearly falls outside the stated window.",
    alternateInterpretation: "No credible alternate interpretation. The timeline is clear and the deadline is unambiguous.",
    marketPriceBehavior: "Rose from 35% to 70% through mission milestones. Peaked at 80% after successful collection. Crashed to 10% when delay was announced.",
  },
  {
    id: "case-018",
    date: "2026-03-10",
    difficulty: 5,
    question: "Will the US national debt exceed $40 trillion before October 1, 2025?",
    resolutionCriteria: "Resolves YES if the total US federal debt outstanding exceeds $40 trillion at any point before October 1, 2025, as reported by the US Treasury's Daily Treasury Statement or Monthly Treasury Statement.",
    timeline: [
      { date: "Jun 2025", description: "Debt ceiling reached. Treasury begins 'extraordinary measures.' Official debt count frozen at $36.8T." },
      { date: "Jul 2025", description: "Analysts estimate actual federal obligations including suspended intergovernmental transfers exceed $40T." },
      { date: "Sep 2025", description: "Congress raises debt ceiling. Treasury backfills suspended obligations. Official debt jumps to $41.2T overnight." },
      { date: "Sep 28, 2025", description: "Treasury records show $41.2T as of September 28." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "indeterminate",
    explanation: "During the debt ceiling period, the official Treasury figures were artificially frozen. The debt 'exceeded' $40T only after the ceiling was raised, but the underlying obligations may have surpassed $40T earlier during the freeze. The resolution criteria relied on Treasury reports, which showed the figure only after the ceiling was raised. Whether the debt 'exceeded' $40T before October 1 depends on whether you count the artificial freeze or the economic reality.",
    alternateInterpretation: "The Treasury Daily Statement showed $41.2T on September 28, which is before October 1. The criteria specified Treasury reports as the source. The report shows the threshold was met in time.",
    marketPriceBehavior: "Stable at 75% until debt ceiling hit. Dropped to 45% during freeze uncertainty. Surged to 95% when ceiling was raised.",
  },
  {
    id: "case-019",
    date: "2026-03-11",
    difficulty: 4,
    question: "Will any EU member state hold a binding referendum on EU membership in 2025?",
    resolutionCriteria: "Resolves YES if any EU member state conducts a legally binding popular referendum specifically on whether to remain in or leave the European Union during calendar year 2025. Source: official election commission of the relevant country.",
    timeline: [
      { date: "Apr 2025", description: "Netherlands announces 'Advisory Referendum on EU Treaty Reforms' for September 2025." },
      { date: "Sep 2025", description: "Referendum held. Question: 'Do you support the proposed EU treaty amendments that would expand qualified majority voting?'" },
      { date: "Sep 2025", description: "60% vote NO. Government states result is 'advisory only' but politically binding." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "The referendum was advisory, not legally binding. It was about treaty amendments, not EU membership. The criteria required a 'legally binding' referendum 'specifically on whether to remain in or leave the EU.' Neither condition was met.",
    alternateInterpretation: "One might stretch the argument that rejecting deeper integration is implicitly about EU membership terms, but this is too indirect to satisfy criteria explicitly requiring a membership referendum.",
    marketPriceBehavior: "Brief spike to 30% on Netherlands announcement. Quickly fell to 8% when question text and advisory nature were clarified.",
  },
  {
    id: "case-020",
    date: "2026-03-12",
    difficulty: 5,
    question: "Will an AI system score above 90th percentile on the US Medical Licensing Examination (USMLE) Step 2 CK by end of 2025?",
    resolutionCriteria: "Resolves YES if a published peer-reviewed paper demonstrates an AI system achieving above the 90th percentile score on a full, standard USMLE Step 2 CK examination (or validated equivalent using official NBME questions) by December 31, 2025. Source: peer-reviewed publication in a medical or AI journal.",
    timeline: [
      { date: "May 2025", description: "Research lab publishes paper showing AI scoring 92nd percentile on 'USMLE Step 2 CK practice examination.'" },
      { date: "Jun 2025", description: "NBME clarifies that practice exams use retired questions and may not reflect current exam difficulty." },
      { date: "Aug 2025", description: "Authors respond that retired questions are 'validated equivalent' per their study methodology." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "misresolved",
    correctFlaw: "definition_ambiguity",
    explanation: "The criteria specified 'full, standard USMLE Step 2 CK examination (or validated equivalent using official NBME questions).' Practice exams using retired questions are not the 'standard' examination, and whether they constitute a 'validated equivalent' is undefined. The authors self-declared equivalence without NBME validation. The criteria lacked a clear definition of what constitutes a validated equivalent.",
    alternateInterpretation: "The questions were official NBME questions (albeit retired). A practice exam composed entirely of official questions could reasonably be considered a validated equivalent, especially since no one can take the real exam as an AI system.",
    marketPriceBehavior: "Rose to 78% on publication. Dipped to 55% on NBME clarification. Settled at 65% with ongoing debate.",
  },
  {
    id: "case-021",
    date: "2026-03-13",
    difficulty: 3,
    question: "Will oil prices (Brent crude) average above $90/barrel for any calendar month in 2025?",
    resolutionCriteria: "Resolves YES if the average daily closing price of Brent crude oil exceeds $90 per barrel for any complete calendar month in 2025. Source: ICE Brent Crude futures front-month contract closing prices.",
    timeline: [
      { date: "Jul 2025", description: "Brent crude averages $91.40 for the month based on daily closes." },
      { date: "Jul 2025", description: "However, the front-month contract rolled from August to September delivery mid-month, creating a price discontinuity." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The criteria specified 'front-month contract closing prices.' Contract rolls are standard in futures markets, and the front-month contract averaged above $90 using the standard continuous front-month series. This is the industry-standard methodology for calculating monthly averages.",
    alternateInterpretation: "One could argue the roll distorted the average, but this is how all major commodity benchmarks are calculated. No credible dispute exists.",
    marketPriceBehavior: "Fluctuated between 35-55% through H1. Jumped to 80% in early July as prices surged. Settled at 95% before month-end.",
  },
  {
    id: "case-022",
    date: "2026-03-14",
    difficulty: 4,
    question: "Will the WHO recommend a universal COVID-19 booster for all adults in 2025?",
    resolutionCriteria: "Resolves YES if the WHO's Strategic Advisory Group of Experts on Immunization (SAGE) issues a recommendation for all adults globally to receive a COVID-19 booster dose during 2025. 'All adults' means without age or risk-group restrictions. Source: WHO SAGE meeting report or policy brief.",
    timeline: [
      { date: "Mar 2025", description: "SAGE recommends booster for adults over 50 and immunocompromised individuals." },
      { date: "Jun 2025", description: "New variant emerges. SAGE expands recommendation to 'all adults in countries with high transmission.'" },
      { date: "Sep 2025", description: "SAGE issues update: 'All adults should consider a booster dose' with language noting individual risk assessment." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "None of the SAGE recommendations met the criteria of a universal recommendation for 'all adults' without restrictions. The March recommendation was age-restricted, June was geographically restricted, and September used 'should consider' language with individual risk assessment, not a universal recommendation.",
    alternateInterpretation: "The September language of 'all adults should consider' is close to universal, but 'should consider' differs materially from a recommendation that all adults receive the booster.",
    marketPriceBehavior: "Started at 25%. Rose to 45% on variant news. Peaked at 55% on September update. Fell to 20% when language was parsed.",
  },
  {
    id: "case-023",
    date: "2026-03-15",
    difficulty: 5,
    question: "Will any self-driving taxi service operate continuously for 6+ months in a US city with >1M population without a safety-related suspension by end of 2025?",
    resolutionCriteria: "Resolves YES if a fully autonomous (SAE Level 4+) taxi service operates for at least 6 consecutive months in a US city with population over 1 million without any regulatory suspension, voluntary safety pause exceeding 48 hours, or government-ordered investigation that halts operations. Source: company filings, NHTSA records, or local regulatory body.",
    timeline: [
      { date: "Jan-Jun 2025", description: "Waymo operates in San Francisco (pop. 870K city / 4.7M metro)." },
      { date: "Apr 2025", description: "Waymo pauses operations for 36 hours after a software update to 'validate system performance.'" },
      { date: "Jul 2025", description: "Waymo passes 6-month mark with only the 36-hour pause." },
    ],
    officialResolution: "Resolved NO (San Francisco city population under 1M)",
    correctClassification: "misresolved",
    correctFlaw: "definition_ambiguity",
    explanation: "The criteria said 'US city with >1M population' without specifying whether this refers to city proper or metropolitan statistical area. San Francisco's city proper population is ~870K but its metro area exceeds 4.7M. Using metro area (common in business and regulatory contexts) would qualify; using city proper would not. The resolution used city proper without justification for this choice.",
    alternateInterpretation: "In common usage and Census Bureau classifications, 'city population' typically refers to the incorporated city's population, not the metro area. The resolution's use of city proper is the more natural reading.",
    marketPriceBehavior: "Traded at 45% through mid-2025. Rose to 70% as Waymo approached 6 months. Crashed to 30% on population technicality debate.",
  },
  {
    id: "case-024",
    date: "2026-03-16",
    difficulty: 3,
    question: "Will Argentina's annual inflation rate fall below 100% by December 2025?",
    resolutionCriteria: "Resolves YES if Argentina's year-over-year consumer price inflation rate falls below 100% for the December 2025 reading, as reported by INDEC (Instituto Nacional de Estadística y Censos). Source: INDEC official CPI release.",
    timeline: [
      { date: "Jan 2026", description: "INDEC reports December 2025 YoY inflation at 94.3%." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The December 2025 YoY inflation rate of 94.3% is clearly below 100%. The source (INDEC) matches the criteria. No ambiguity exists.",
    alternateInterpretation: "Some economists dispute INDEC's methodology, but the criteria specified INDEC as the authoritative source, making external estimates irrelevant.",
    marketPriceBehavior: "Started at 40%. Gradually rose as monthly rates decelerated through 2025. Reached 80% by November.",
  },
  {
    id: "case-025",
    date: "2026-03-17",
    difficulty: 4,
    question: "Will the US and China sign a bilateral agreement on AI safety before the end of 2025?",
    resolutionCriteria: "Resolves YES if the US and China sign a formal bilateral agreement, memorandum of understanding, or joint statement specifically addressing AI safety, including provisions for risk mitigation or information sharing on frontier AI systems. Both heads of state or designated cabinet-level officials must sign. Source: US State Department or Chinese Ministry of Foreign Affairs.",
    timeline: [
      { date: "Aug 2025", description: "US and China issue 'Joint Understanding on Artificial Intelligence Cooperation' at bilateral summit." },
      { date: "Aug 2025", description: "Document signed by US Secretary of Commerce and Chinese Minister of Science and Technology." },
      { date: "Sep 2025", description: "Analysis reveals the document addresses AI cooperation broadly but safety provisions are limited to a single paragraph pledging 'future dialogue on AI safety topics.'" },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "misresolved",
    correctFlaw: "procedural_substantive_confusion",
    explanation: "The document was signed by appropriate officials and is titled as an AI agreement, satisfying procedural requirements. However, the criteria required the agreement to 'specifically address AI safety, including provisions for risk mitigation or information sharing on frontier AI systems.' A single paragraph pledging future dialogue does not constitute substantive provisions for risk mitigation or information sharing.",
    alternateInterpretation: "The agreement does mention AI safety and pledges dialogue, which could be considered 'addressing' the topic. The criteria didn't specify a minimum depth of coverage.",
    marketPriceBehavior: "Jumped to 75% on summit announcement. Rose to 88% when signing was confirmed. Dropped to 60% as content analysis emerged.",
  },
];
