import { DailyCase } from "./types";

export const CASES_BATCH2: DailyCase[] = [
  {
    id: "case-026",
    date: "2026-03-18",
    difficulty: 4,
    question: "Will any nuclear fusion reactor achieve sustained net energy gain (Q>1) for more than 60 seconds by end of 2025?",
    resolutionCriteria: "Resolves YES if a fusion reactor achieves a sustained plasma with Q>1 (energy output exceeds energy input to the plasma) for a continuous period exceeding 60 seconds, as reported in a peer-reviewed publication or official facility press release by December 31, 2025.",
    timeline: [
      { date: "Jul 2025", description: "China's EAST tokamak achieves Q=1.05 plasma sustained for 72 seconds." },
      { date: "Aug 2025", description: "EAST team publishes results. Q factor calculation uses 'energy input to plasma' excluding magnet cooling and heating system losses." },
      { date: "Sep 2025", description: "Critics argue total facility energy input (including all support systems) yields Q=0.3." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The criteria specified 'energy input to the plasma,' which is the standard physics definition of Q factor used in fusion research. The EAST result of Q=1.05 using plasma-input methodology is the standard measure. Total facility energy (engineering Q) is a different metric not specified in the criteria.",
    alternateInterpretation: "The distinction between scientific Q and engineering Q is significant for practical relevance, but the criteria were technically precise in specifying plasma energy input.",
    marketPriceBehavior: "Low at 12% early 2025. Jumped to 65% on EAST announcement. Debated between 50-75% on Q definition controversy.",
  },
  {
    id: "case-027",
    date: "2026-03-19",
    difficulty: 3,
    question: "Will the US unemployment rate exceed 5.0% at any point in 2025?",
    resolutionCriteria: "Resolves YES if the Bureau of Labor Statistics (BLS) reports a monthly US unemployment rate (U-3) exceeding 5.0% for any month in 2025. Source: BLS Employment Situation Summary.",
    timeline: [
      { date: "Aug 2025", description: "BLS reports July 2025 unemployment at 5.1%." },
      { date: "Sep 2025", description: "BLS revises July figure to 4.9% in annual benchmark revision." },
    ],
    officialResolution: "Resolved YES (based on initial July report)",
    correctClassification: "misresolved",
    correctFlaw: "retroactive_reinterpretation",
    explanation: "The criteria said 'BLS reports' without specifying whether initial or revised figures should be used. The initial report showed 5.1%, but the benchmark revision corrected this to 4.9%. At time of resolution, the most current BLS figure for July was 4.9%, meaning the threshold was never actually exceeded according to the best available data.",
    alternateInterpretation: "BLS did 'report' 5.1% in its initial release. The word 'reports' could reasonably refer to any official BLS publication, including initial estimates that are later revised.",
    marketPriceBehavior: "Spiked to 90% on initial July report. Dropped to 45% after revision. Resolved YES, causing significant controversy.",
  },
  {
    id: "case-028",
    date: "2026-03-20",
    difficulty: 5,
    question: "Will the International Court of Justice issue an advisory opinion declaring climate change inaction a violation of international law by end of 2025?",
    resolutionCriteria: "Resolves YES if the ICJ issues an advisory opinion that explicitly states that states' failure to take adequate action on climate change constitutes a violation of their obligations under international law. 'Explicitly states' means direct declaratory language, not implied conclusions. Source: ICJ official advisory opinion text.",
    timeline: [
      { date: "Jun 2025", description: "ICJ hearings conclude with 98 states and 12 international organizations participating." },
      { date: "Nov 2025", description: "ICJ issues advisory opinion. Key language: 'States are under an obligation to ensure that activities within their jurisdiction do not cause significant harm to the environment of other States. The failure to adopt measures consistent with this obligation may engage state responsibility.'" },
      { date: "Nov 2025", description: "Legal scholars split on whether 'may engage state responsibility' constitutes an explicit declaration of violation." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "The criteria required 'explicit' declaratory language stating inaction 'constitutes a violation.' The ICJ used 'may engage state responsibility,' which is conditional and hedged language. 'May' is not 'does.' The resolution correctly identified the gap between the ICJ's cautious language and the criteria's explicit standard.",
    alternateInterpretation: "In ICJ advisory opinion practice, 'may engage state responsibility' is as strong as the court typically gets. The institution's norms favor cautious language even for firm conclusions. But the criteria demanded explicit declaration, not institutional-norm-relative language.",
    marketPriceBehavior: "Traded at 55% through hearings. Rose to 68% on opinion announcement. Dropped to 30% as language was analyzed.",
  },
  {
    id: "case-029",
    date: "2026-03-21",
    difficulty: 3,
    question: "Will Apple release a foldable iPhone in 2025?",
    resolutionCriteria: "Resolves YES if Apple announces and begins selling a foldable iPhone (a smartphone with a flexible display that folds) in calendar year 2025. Source: Apple press release or product page on apple.com.",
    timeline: [
      { date: "Sep 2025", description: "Apple announces iPhone 17 lineup. No foldable model." },
      { date: "Nov 2025", description: "Reliable leakers report foldable iPhone prototype exists but launch is delayed to 2026." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "No foldable iPhone was announced or sold in 2025. Prototype reports and leaks are irrelevant to the criteria which required an announcement and sales.",
    alternateInterpretation: "None. The criteria are clear and the event did not occur.",
    marketPriceBehavior: "Started at 20%. Brief spike to 35% on supply chain rumors in March. Gradually fell to 5% after September event.",
  },
  {
    id: "case-030",
    date: "2026-03-22",
    difficulty: 5,
    question: "Will the global carbon credit market exceed $1 trillion in annual transaction volume by end of 2025?",
    resolutionCriteria: "Resolves YES if the total value of carbon credit transactions (compliance and voluntary markets combined) exceeds $1 trillion for calendar year 2025. Source: World Bank 'State and Trends of Carbon Pricing' report or Refinitiv carbon market analysis.",
    timeline: [
      { date: "Feb 2026", description: "World Bank report estimates 2025 carbon market at $980 billion." },
      { date: "Feb 2026", description: "Refinitiv analysis estimates 2025 carbon market at $1.05 trillion, using a broader definition that includes bilateral OTC transactions." },
    ],
    officialResolution: "Resolved NO (based on World Bank figure)",
    correctClassification: "indeterminate",
    explanation: "The criteria listed two sources (World Bank OR Refinitiv) with different methodologies producing different results — one above and one below the threshold. The resolution chose the World Bank figure without justification for preferring one source over the other. Since the criteria presented them as equivalent alternatives, the case is genuinely indeterminate.",
    alternateInterpretation: "The 'or' might imply a preference order (World Bank primary, Refinitiv secondary). The World Bank is arguably the more authoritative institutional source for carbon pricing data.",
    marketPriceBehavior: "Gradually rose from 30% to 60% through 2025 as carbon markets grew. Split between 45-55% at year end as estimates diverged.",
  },
  {
    id: "case-031",
    date: "2026-03-23",
    difficulty: 4,
    question: "Will Russia and Ukraine agree to a formal ceasefire by December 31, 2025?",
    resolutionCriteria: "Resolves YES if Russia and Ukraine both sign or publicly agree to a formal ceasefire agreement that halts active hostilities. Both parties must acknowledge the agreement. 'Formal' means a documented agreement, not a unilateral pause. Source: official government statements from both parties or UN confirmation.",
    timeline: [
      { date: "Aug 2025", description: "Mediators announce both sides have agreed to a 'humanitarian pause' lasting 30 days." },
      { date: "Sep 2025", description: "Russia's foreign ministry calls it a 'temporary operational pause,' not a ceasefire." },
      { date: "Sep 2025", description: "Ukraine's president refers to it as a 'ceasefire step.'" },
      { date: "Oct 2025", description: "Fighting resumes after 28 days. No formal document was ever signed." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "The criteria required a 'formal' ceasefire with both parties acknowledging the agreement. No formal document was signed, the parties used different terminology, and the pause ended before the 30-day period. The criteria were clear and not met.",
    alternateInterpretation: "The humanitarian pause could be viewed as a de facto ceasefire, but the criteria explicitly required formal documentation and mutual acknowledgment, neither of which occurred.",
    marketPriceBehavior: "Low at 8% most of 2025. Spiked to 35% on humanitarian pause announcement. Fell to 12% when terminology disagreements emerged.",
  },
  {
    id: "case-032",
    date: "2026-03-24",
    difficulty: 4,
    question: "Will any major US bank fail or be placed into FDIC receivership in 2025?",
    resolutionCriteria: "Resolves YES if any US bank with total assets exceeding $50 billion is closed by regulators or placed into FDIC receivership during 2025. Source: FDIC Failed Bank List.",
    timeline: [
      { date: "May 2025", description: "Regional bank with $62 billion in assets faces liquidity crisis." },
      { date: "Jun 2025", description: "FDIC brokers a 'purchase and assumption' agreement where a larger bank acquires the troubled bank over a weekend." },
      { date: "Jun 2025", description: "FDIC does not list the bank on its Failed Bank List, as the P&A prevented formal receivership." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "The criteria specified the FDIC Failed Bank List as the source. The bank was not placed into receivership or listed as failed. A purchase and assumption is a different regulatory mechanism. The criteria were precise about the resolution mechanism.",
    alternateInterpretation: "The bank effectively failed — it could not continue operations independently and required emergency regulatory intervention. But the specific mechanism (P&A vs receivership) matters under the stated criteria.",
    marketPriceBehavior: "Spiked to 70% during the liquidity crisis weekend. Dropped to 15% when P&A structure was announced Monday morning.",
  },
  {
    id: "case-033",
    date: "2026-03-25",
    difficulty: 5,
    question: "Will a deepfake video directly and demonstrably influence the outcome of a national election in 2025?",
    resolutionCriteria: "Resolves YES if credible post-election analysis in a peer-reviewed journal or report by an internationally recognized election monitoring organization demonstrates that a specific deepfake video materially influenced voter behavior sufficient to change the outcome of a national election held in 2025. Source: peer-reviewed publication or report by OSCE, Carter Center, or equivalent.",
    timeline: [
      { date: "Sep 2025", description: "Deepfake video of a presidential candidate in Country A goes viral 48 hours before election." },
      { date: "Oct 2025", description: "Candidate loses by 1.2% margin." },
      { date: "Nov 2025", description: "OSCE report states deepfake 'likely contributed to misinformation environment' but cannot 'definitively attribute the outcome to any single factor.'" },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "The criteria required demonstration that a deepfake 'materially influenced voter behavior sufficient to change the outcome.' The OSCE report explicitly stated it could not definitively attribute the outcome to the deepfake. Correlation between the deepfake and the result does not meet the causal standard required.",
    alternateInterpretation: "The 1.2% margin and viral deepfake timing make it highly plausible, but the criteria required demonstrated causation, not plausible correlation. This is an extremely high evidentiary bar that may be practically impossible to meet.",
    marketPriceBehavior: "Jumped to 60% after the deepfake incident. Settled at 40% as analysts debated causation. Resolved NO at 25%.",
  },
  {
    id: "case-034",
    date: "2026-03-26",
    difficulty: 3,
    question: "Will Bitcoin's price exceed $150,000 at any point in 2025?",
    resolutionCriteria: "Resolves YES if Bitcoin (BTC) trades above $150,000 USD on any major exchange (Coinbase, Binance, or Kraken) at any point during 2025. Source: exchange API price data.",
    timeline: [
      { date: "Oct 2025", description: "Bitcoin reaches $152,400 on Binance for approximately 4 minutes during a flash spike." },
      { date: "Oct 2025", description: "Coinbase and Kraken peak prices during the same period were $149,800 and $148,900 respectively." },
      { date: "Oct 2025", description: "Binance acknowledges the spike was driven by a large market order with thin order book conditions." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The criteria stated 'any major exchange (Coinbase, Binance, or Kraken)' and 'at any point.' The Binance price of $152,400 satisfies both conditions. The criteria did not require sustained pricing or multi-exchange confirmation. Flash spikes on legitimate exchanges count under these rules.",
    alternateInterpretation: "One could argue a 4-minute flash spike on thin liquidity doesn't reflect Bitcoin's true market price, but the criteria were deliberately broad ('any point,' 'any major exchange').",
    marketPriceBehavior: "Rose from 30% to 55% through 2025. Jumped to 99% after flash spike. Brief debate about validity settled quickly.",
  },
  {
    id: "case-035",
    date: "2026-03-27",
    difficulty: 4,
    question: "Will the EU Digital Markets Act result in Apple allowing third-party app stores on iOS in 2025?",
    resolutionCriteria: "Resolves YES if Apple permits the installation and operation of third-party app stores (alternative marketplaces) on iOS devices sold in the EU during 2025, as required by DMA compliance. Source: Apple developer documentation or European Commission compliance assessment.",
    timeline: [
      { date: "Mar 2025", description: "Apple allows 'alternative marketplaces' in the EU via notarization process." },
      { date: "May 2025", description: "European Commission opens investigation into whether Apple's Core Technology Fee and notarization requirements constitute effective compliance." },
      { date: "Sep 2025", description: "Commission preliminary finding: Apple's implementation 'does not fully comply with DMA obligations' due to restrictive conditions." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "indeterminate",
    explanation: "Apple technically permits third-party app stores, satisfying the literal criteria. But the Commission found the implementation doesn't fully comply with DMA, suggesting the permission is too restrictive to constitute genuine allowance. The criteria asked whether Apple 'permits installation and operation' — it does, with significant restrictions. Whether restricted permission counts as permission is genuinely ambiguous.",
    alternateInterpretation: "Third-party app stores do exist and function on iOS in the EU. Users can and do install them. The criteria asked about permission, not about the quality or completeness of that permission.",
    marketPriceBehavior: "High at 85% from start given Apple's announced plans. Stable until Commission investigation. Dropped to 65% on non-compliance finding.",
  },
  {
    id: "case-036",
    date: "2026-03-28",
    difficulty: 5,
    question: "Will any country successfully test an anti-satellite weapon that creates trackable orbital debris in 2025?",
    resolutionCriteria: "Resolves YES if any nation conducts a kinetic anti-satellite (ASAT) weapon test that destroys or damages a satellite and creates debris tracked by the US Space Surveillance Network during 2025. Source: US Space Command statement, NORAD tracking data, or official government acknowledgment of the test.",
    timeline: [
      { date: "Jun 2025", description: "Country B launches a missile that passes within 50km of a defunct satellite." },
      { date: "Jun 2025", description: "US Space Command characterizes the test as a 'close approach ASAT demonstration' but no physical contact or debris detected." },
      { date: "Aug 2025", description: "Country B claims the test demonstrated 'anti-satellite capability' in state media." },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "The criteria required the test to 'destroy or damage a satellite' and create 'trackable orbital debris.' Neither occurred — the missile passed near the satellite but made no contact. A capability demonstration is not a destructive test. The resolution correctly applied the criteria.",
    alternateInterpretation: "Country B's characterization of it as an ASAT test is irrelevant since the criteria specified physical outcomes (destruction/damage and debris), not intent or capability demonstration.",
    marketPriceBehavior: "Brief spike to 40% on test reports. Quickly fell to 10% when close-approach nature was confirmed.",
  },
  {
    id: "case-037",
    date: "2026-03-29",
    difficulty: 3,
    question: "Will global smartphone shipments exceed 1.3 billion units in 2025?",
    resolutionCriteria: "Resolves YES if total global smartphone shipments for calendar year 2025 exceed 1.3 billion units as reported by IDC's Worldwide Quarterly Mobile Phone Tracker. Source: IDC press release or report.",
    timeline: [
      { date: "Jan 2026", description: "IDC reports 2025 global smartphone shipments at 1.31 billion units." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "IDC reported 1.31 billion, exceeding 1.3 billion. Source matches criteria. No ambiguity.",
    alternateInterpretation: "None. Clean resolution.",
    marketPriceBehavior: "Traded around 60-70% most of 2025. Rose to 85% after strong Q3 data. Settled at 92% before report.",
  },
  {
    id: "case-038",
    date: "2026-03-30",
    difficulty: 5,
    question: "Will a human-level AI (AGI) be achieved by any lab by end of 2025, as determined by passing a standardized AGI benchmark?",
    resolutionCriteria: "Resolves YES if an AI system passes a standardized AGI benchmark accepted by the broader AI research community. 'Accepted by the broader AI research community' means the benchmark has been referenced in at least 50 peer-reviewed papers. Source: benchmark results published by the developing organization with independent verification.",
    timeline: [
      { date: "Sep 2025", description: "Lab X announces system that scores 85% on ARC-AGI benchmark." },
      { date: "Oct 2025", description: "Debate erupts over whether ARC-AGI constitutes an 'AGI benchmark' — it tests specific reasoning capabilities, not general intelligence." },
      { date: "Nov 2025", description: "ARC-AGI has been referenced in 67 peer-reviewed papers. Its creator states it is 'a measure of fluid intelligence, one component of AGI, not AGI itself.'" },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "indeterminate",
    explanation: "The criteria required a 'standardized AGI benchmark accepted by the broader AI research community.' ARC-AGI meets the citation threshold (67>50) but its creator explicitly states it doesn't measure AGI. The research community is split on whether any existing benchmark measures AGI. The criteria assumed a consensus AGI benchmark exists, creating a question that may be structurally unresolvable.",
    alternateInterpretation: "If no benchmark is 'accepted' as measuring AGI, the question trivially resolves NO regardless of AI capabilities. The resolution of NO could be correct by default since the benchmark acceptance condition itself isn't met.",
    marketPriceBehavior: "Started at 8%. Rose to 25% on Lab X announcement. Fell back to 12% as benchmark validity was debated.",
  },
  {
    id: "case-039",
    date: "2026-03-31",
    difficulty: 4,
    question: "Will the US Federal Reserve cut interest rates by more than 100 basis points total in 2025?",
    resolutionCriteria: "Resolves YES if the cumulative federal funds rate reductions by the Federal Reserve during calendar year 2025 exceed 100 basis points. Measured from the rate at January 1, 2025 to the lowest rate reached during the year. Source: Federal Reserve FOMC press releases.",
    timeline: [
      { date: "Jan 2025", description: "Federal funds rate starts at 4.25-4.50% (target range)." },
      { date: "Mar 2025", description: "Fed cuts 25bp to 4.00-4.25%." },
      { date: "Jun 2025", description: "Fed cuts 50bp to 3.50-3.75%." },
      { date: "Sep 2025", description: "Fed cuts 25bp to 3.25-3.50%." },
      { date: "Dec 2025", description: "Fed cuts 25bp to 3.00-3.25%. Total cuts: 125bp." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "Total cumulative cuts of 125bp exceed the 100bp threshold. Using the upper bound (4.50% to 3.25% = 125bp) or lower bound (4.25% to 3.00% = 125bp), the result is the same. Clean resolution.",
    alternateInterpretation: "None. The arithmetic is clear and the sources are unambiguous.",
    marketPriceBehavior: "Started at 30%. Rose with each cut. Crossed 80% after the September cut. Settled at 95% before December meeting.",
  },
  {
    id: "case-040",
    date: "2026-04-01",
    difficulty: 4,
    question: "Will more than 10 million electric vehicles be sold in China in 2025?",
    resolutionCriteria: "Resolves YES if total new energy vehicle (NEV) sales in China exceed 10 million units in 2025. NEV includes battery electric vehicles (BEV) and plug-in hybrid electric vehicles (PHEV). Source: China Association of Automobile Manufacturers (CAAM) annual report.",
    timeline: [
      { date: "Jan 2026", description: "CAAM reports 2025 NEV sales at 12.8 million units." },
      { date: "Jan 2026", description: "Of the 12.8M, approximately 4.1M were PHEVs including extended-range electric vehicles (EREVs)." },
      { date: "Feb 2026", description: "Debate arises whether EREVs should count as 'electric vehicles' since they contain conventional engines." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The criteria defined the scope as NEV including BEV and PHEV. CAAM classifies EREVs within the PHEV category. Even excluding all PHEVs, BEV sales alone (~8.7M) wouldn't meet the threshold, but the criteria explicitly included PHEVs. The resolution correctly followed the stated definitions.",
    alternateInterpretation: "If the question had said 'electric vehicles' without the NEV/PHEV clarification, there would be a genuine debate about EREVs. But the criteria explicitly included PHEVs.",
    marketPriceBehavior: "Started high at 75% given strong 2024 trends. Rose to 90% by mid-year. Never seriously contested.",
  },
  {
    id: "case-041",
    date: "2026-04-02",
    difficulty: 5,
    question: "Will the Doomsday Clock be set closer to midnight than 90 seconds in January 2026?",
    resolutionCriteria: "Resolves YES if the Bulletin of the Atomic Scientists sets the Doomsday Clock to less than 90 seconds to midnight in their January 2026 announcement. Source: Bulletin of the Atomic Scientists official announcement.",
    timeline: [
      { date: "Jan 2026", description: "Bulletin announces the clock moves to 89 seconds to midnight." },
      { date: "Jan 2026", description: "Critics note this is the first time a sub-minute increment (1 second) has been used, traditionally the clock moves in 30-second or larger increments." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "89 seconds is less than 90 seconds. The criteria didn't specify increment conventions. The Bulletin's announcement is the specified source and clearly states the new setting.",
    alternateInterpretation: "The 1-second move could be seen as symbolic rather than substantive, but the criteria asked about the clock setting, not the magnitude of change.",
    marketPriceBehavior: "Traded around 55% through 2025. Rose to 70% after escalatory geopolitical events in Q4. Settled at 65% before announcement.",
  },
  {
    id: "case-042",
    date: "2026-04-03",
    difficulty: 3,
    question: "Will Netflix subscriber count exceed 300 million by end of Q4 2025?",
    resolutionCriteria: "Resolves YES if Netflix reports more than 300 million global paid subscribers in their Q4 2025 earnings report. Source: Netflix quarterly earnings press release.",
    timeline: [
      { date: "Jan 2026", description: "Netflix Q4 2025 earnings report shows 312 million global paid subscribers." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "312 million exceeds 300 million. Source is Netflix's own earnings report as specified. No ambiguity.",
    alternateInterpretation: "None.",
    marketPriceBehavior: "Traded around 65% at start of 2025. Gradually rose with each quarterly report showing growth. Reached 90% after Q3 showed 295M.",
  },
  {
    id: "case-043",
    date: "2026-04-04",
    difficulty: 5,
    question: "Will any country implement a central bank digital currency (CBDC) for general public use by end of 2025?",
    resolutionCriteria: "Resolves YES if any country launches a CBDC available for general public retail transactions (not limited to wholesale/interbank or pilot programs with restricted participation) by December 31, 2025. Source: central bank official announcement.",
    timeline: [
      { date: "Jul 2025", description: "Nigeria expands eNaira beyond pilot to all banks nationwide." },
      { date: "Aug 2025", description: "eNaira wallet registrations reach 22 million but active usage remains under 2% of transactions." },
      { date: "Sep 2025", description: "Analysts debate whether eNaira constitutes 'general public use' given extremely low adoption despite universal availability." },
    ],
    officialResolution: "Resolved YES",
    correctClassification: "correct",
    explanation: "The criteria specified 'available for general public retail transactions,' not 'widely used.' The eNaira is available to the general public and can be used for retail transactions. Low adoption doesn't negate availability. The resolution correctly distinguished between availability and adoption.",
    alternateInterpretation: "One could argue that a CBDC with 2% usage isn't meaningfully 'for general public use' — it's technically available but not practically implemented. But the criteria asked about launch and availability, not adoption metrics.",
    marketPriceBehavior: "Already at 70% given Nigeria's existing eNaira. Rose to 85% on expansion announcement. Minor debate on adoption kept it from 95%.",
  },
  {
    id: "case-044",
    date: "2026-04-05",
    difficulty: 4,
    question: "Will a major hurricane (Category 4+) make landfall in the continental US in 2025?",
    resolutionCriteria: "Resolves YES if a hurricane classified as Category 4 or 5 on the Saffir-Simpson scale at time of landfall makes landfall on the continental United States during the 2025 Atlantic hurricane season. Source: National Hurricane Center official advisory at landfall.",
    timeline: [
      { date: "Sep 2025", description: "Hurricane makes landfall near Galveston, TX. NHC advisory at landfall classifies it as Category 4 with 130 mph sustained winds." },
      { date: "Sep 2025", description: "Post-season analysis by NHC revises landfall intensity to Category 3 (125 mph) based on detailed surface observations." },
    ],
    officialResolution: "Resolved YES (based on real-time advisory)",
    correctClassification: "misresolved",
    correctFlaw: "retroactive_reinterpretation",
    explanation: "The criteria specified 'National Hurricane Center official advisory at landfall,' which showed Category 4. However, NHC's post-season reanalysis — which is their official final record — downgraded it to Category 3. The question is whether the 'advisory at landfall' or the 'official final record' represents the NHC's authoritative assessment. The resolution chose the real-time advisory, but the post-season analysis is NHC's definitive answer.",
    alternateInterpretation: "The criteria specifically said 'advisory at landfall,' not post-season reanalysis. Real-time advisories are official NHC products, and the criteria appears to deliberately specify this timing to avoid exactly this kind of revision issue.",
    marketPriceBehavior: "Spiked to 95% as hurricane approached at Cat 4. Dropped to 60% months later when reanalysis was published.",
  },
  {
    id: "case-045",
    date: "2026-04-06",
    difficulty: 3,
    question: "Will the Mars Perseverance rover discover organic molecules that cannot be explained by known abiotic processes by end of 2025?",
    resolutionCriteria: "Resolves YES if NASA announces that Perseverance has detected organic molecules in Martian samples that cannot be adequately explained by known abiotic (non-biological) chemical processes, as published in a NASA press release or peer-reviewed paper by December 31, 2025.",
    timeline: [
      { date: "Jun 2025", description: "Perseverance detects complex organic molecules in Jezero Crater delta sediments." },
      { date: "Aug 2025", description: "NASA press release: 'Organic molecules detected that are consistent with biological processes, though abiotic origins cannot be fully ruled out.'" },
    ],
    officialResolution: "Resolved NO",
    correctClassification: "correct",
    explanation: "The criteria required molecules that 'cannot be explained by known abiotic processes.' NASA's statement explicitly says 'abiotic origins cannot be fully ruled out,' meaning known abiotic processes can still explain the findings. The criteria set a high bar (cannot be explained) that wasn't met.",
    alternateInterpretation: "'Consistent with biological processes' is suggestive but not sufficient under criteria requiring exclusion of abiotic explanations.",
    marketPriceBehavior: "Low at 15% most of the year. Briefly spiked to 35% on detection news. Settled at 12% after NASA language was parsed.",
  },
];
